module.exports = [
	{
		"name":"Afghanistan",
		"iso2":"AF",
		"states":[
			"Zabul",
			"Samangan",
			"Badgis",
			"Farah",
			"Kabul",
			"Badakhshan",
			"Khawst",
			"Wardag",
			"Bamiyan",
			"Baglan",
			"Sar-e Pul",
			"Nimruz",
			"Takhar",
			"Kunar",
			"Jawzjan",
			"Nangarhar",
			"Lagman",
			"Qunduz",
			"Hilmand",
			"Gawr",
			"Gazni",
			"Lawghar",
			"Balkh",
			"Uruzgan",
			"Paktika",
			"Parwan",
			"Qandahar",
			"Nuristan",
			"Paktiya",
			"Kapisa",
			"Herat",
			"Faryab"
		]
	},
	{
		"name":"Aland Islands",
		"iso2":"AX",
		"states":[]
	},
	{
		"name":"Albania",
		"iso2":"AL",
		"states":[
			"Elbasan",
			"Kucove",
			"Malsi e Madhe",
			"Kavaje",
			"Puke",
			"Tirane",
			"Delvine",
			"Has",
			"Durres",
			"Korce",
			"Bulqize",
			"Mat",
			"Lezhe",
			"Librazhd",
			"Gramsh",
			"Tropoje",
			"Shkoder",
			"Skrapar",
			"Kurbin",
			"Mallakaster",
			"Fier",
			"Kolonje",
			"Permet",
			"Kruje",
			"Vlore",
			"Gjirokaster",
			"Sarande",
			"Kukes",
			"Pogradec",
			"Lushnje",
			"Tepelene",
			"Dibre",
			"Berat",
			"Peqin",
			"Devoll",
			"Mirdite"
		]
	},
	{
		"name":"Algeria",
		"iso2":"DZ",
		"states":[
			"Annabah",
			"Ghardayah",
			"Tibissah",
			"Tilimsan",
			"al-Aghwat",
			"\\'Ayn Tamushanat",
			"Sayda\\'",
			"Khanshalah",
			"at-Tarif",
			"Ouargla",
			"Wilaya d Alger",
			"Wilaya de Bejaia",
			"Warqla",
			"Muaskar",
			"Sidi ban-al-\\'Abbas",
			"Qustantinah",
			"Jilfah",
			"Bashshar",
			"Tinduf",
			"Umm-al-Bawaghi",
			"Wilaya de Constantine",
			"Ilizi",
			"Tisamsilt",
			"Milah",
			"Sakikdah",
			"Satif",
			"Algiers",
			"Qalmah",
			"Tamanghasat",
			"Tizi Wazu",
			"Biskrah",
			"Masilah",
			"\\'Ayn Daflah",
			"al-Wad",
			"Jijili",
			"Suq Ahras",
			"Tibazah",
			"Mustaghanam",
			"Bumardas",
			"Batnah",
			"Oran",
			"al-Bayadh",
			"Naama",
			"Bijayah",
			"Midyah",
			"Blidah",
			"Adrar",
			"al-Jaza\\'ir",
			"Ghalizan",
			"Tiyarat",
			"Burj Bu Arririj",
			"Wahran",
			"Buirah",
			"ash-Shalif"
		]
	},
	{
		"name":"American Samoa",
		"iso2":"AS",
		"states":[
			"Manu\\'a",
			"Western",
			"Swains Island",
			"Eastern"
		]
	},
	{
		"name":"Andorra",
		"iso2":"AD",
		"states":[
			"Sant Julia de Loria",
			"Canillo",
			"Andorra la Vella",
			"Ordino",
			"Les Escaldes",
			"La Massana",
			"Encamp"
		]
	},
	{
		"name":"Angola",
		"iso2":"AO",
		"states":[
			"Moxico",
			"Luanda",
			"Kwanza Norte",
			"Malanje",
			"Bie",
			"Namibe",
			"Cunene",
			"Lunda Norte",
			"Benguela",
			"Huambo",
			"Kuando-Kubango",
			"Huila",
			"Lunda Sul",
			"Cabinda",
			"Uige",
			"Bengo",
			"Zaire",
			"Kwanza Sul"
		]
	},
	{
		"name":"Anguilla",
		"iso2":"AI",
		"states":[
			"Other Provinces"
		]
	},
	{
		"name":"Antarctica",
		"iso2":"AQ",
		"states":[
			"Sector claimed by Norway",
			"Sector claimed by France",
			"Sector claimed by New Zealand",
			"Unclaimed Sector",
			"Sector claimed by Argentina/UK",
			"Sector claimed by Australia",
			"Sector claimed by Argentina/Ch"
		]
	},
	{
		"name":"Antigua And Barbuda",
		"iso2":"AG",
		"states":[
			"Saint John",
			"Saint George",
			"Saint Paul",
			"Saint Peter",
			"Saint Mary",
			"Saint Philip",
			"Barbuda"
		]
	},
	{
		"name":"Argentina",
		"iso2":"AR",
		"states":[
			"San Juan",
			"Chaco",
			"Mendoza",
			"Chubut",
			"San Luis",
			"Neuquen",
			"Misiones",
			"Rio Negro",
			"Formosa",
			"Cordoba",
			"Corrientes",
			"Buenos Aires",
			"Santa Cruz",
			"Tierra del Fuego",
			"Santiago del Estero",
			"La Pampa",
			"Tucuman",
			"Entre Rios",
			"Distrito Federal",
			"Jujuy",
			"Catamarca",
			"Salta",
			"La Rioja",
			"Santa Fe"
		]
	},
	{
		"name":"Armenia",
		"iso2":"AM",
		"states":[
			"Armavir",
			"Syunik",
			"Kotaik",
			"Vayots Dzor",
			"Aragatsotn",
			"Stepanakert",
			"Tavush",
			"Shirak",
			"Lori",
			"Ararat",
			"Gegharkunik",
			"Yerevan"
		]
	},
	{
		"name":"Aruba",
		"iso2":"AW",
		"states":[
			"Aruba"
		]
	},
	{
		"name":"Australia",
		"iso2":"AU",
		"states":[
			"Jannnali",
			"Auckland",
			"Werribee south",
			"Carole Park",
			"Perth",
			"Templestowe",
			"Castle Hill",
			"Chatswood",
			"Wheeler",
			"Victoria",
			"Clayton",
			"Camberwell",
			"Queensland",
			"Tasmania",
			"Balgowlah",
			"Baulkham Hills",
			"Northern Territory",
			"Cherrybrook",
			"Bankstown",
			"Melbourne",
			"Hawthorn",
			"Knoxfield",
			"Collingwood",
			"Balmain",
			"South Australia",
			"Cheltenham",
			"Frenchs Forest",
			"Western Australia",
			"Australian Capital Territory",
			"Caulfield",
			"Bonnet Bay",
			"New South Wales"
		]
	},
	{
		"name":"Austria",
		"iso2":"AT",
		"states":[
			"Vorarlberg",
			"Bundesland Salzburg",
			"Steiermark",
			"Niederosterreich",
			"Salzburg",
			"Schleswig-Holstein",
			"Carinthia",
			"Lower Austria",
			"Tirol",
			"Styria",
			"Bundesland Tirol",
			"Wien",
			"Oberosterreich",
			"Upper Austria",
			"Burgenland",
			"Liezen",
			"Karnten",
			"Bundesland Steiermark"
		]
	},
	{
		"name":"Azerbaijan",
		"iso2":"AZ",
		"states":[
			"Mil-Qarabax",
			"Sirvan",
			"Saki",
			"Mugan-Salyan",
			"Nagorni-Qarabax",
			"Naxcivan",
			"Baki Sahari",
			"Ganja",
			"Abseron",
			"Qazax",
			"Xacmaz",
			"Kalbacar",
			"Lankaran",
			"Ganca",
			"Priaraks"
		]
	},
	{
		"name":"Bahamas The",
		"iso2":"BS",
		"states":[]
	},
	{
		"name":"Bahrain",
		"iso2":"BH",
		"states":[
			"Badiyah",
			"Jidd Hafs",
			"Hidd",
			"al-Manamah",
			"al-Muharraq",
			"Mahama",
			"\\'Isa",
			"Manama",
			"ar-Rifa\\'a",
			"Sitrah"
		]
	},
	{
		"name":"Bangladesh",
		"iso2":"BD",
		"states":[
			"Nawabganj",
			"Jhanaydah",
			"Koks Bazar",
			"Sherpur",
			"Feni",
			"Tangayal",
			"Netrakona",
			"Gopalganj",
			"Jhalakati",
			"Satkhira",
			"Gaybanda",
			"Naral",
			"Jessor",
			"Noakhali",
			"Rajshahi",
			"Sirajganj",
			"Nator",
			"Munshiganj",
			"Bhola",
			"Maimansingh",
			"Chandpur",
			"Khulna",
			"Gazipur",
			"Jaipur Hat",
			"Nilphamari",
			"Kushtiya",
			"Shariatpur",
			"Habiganj",
			"Patuakhali",
			"Narayanganj",
			"Dhaka",
			"Chattagam",
			"Narsingdi",
			"Magura",
			"Dinajpur",
			"Meherpur",
			"Bandarban",
			"Lalmanir Hat",
			"Rajbari",
			"Silhat",
			"Lakshmipur",
			"Panchagarh",
			"Chuadanga",
			"Rangpur",
			"Kishorganj",
			"Thakurgaon",
			"Maulvi Bazar",
			"Chittagong Division",
			"Pabna",
			"Brahman Bariya",
			"Komilla",
			"Bagar Hat",
			"Pirojpur",
			"Manikganj",
			"Rangamati",
			"Jamalpur",
			"Khagrachhari",
			"Bogora",
			"Faridpur",
			"Barguna",
			"Madaripur",
			"Barisal",
			"Naugaon",
			"Sunamganj",
			"Kurigram"
		]
	},
	{
		"name":"Barbados",
		"iso2":"BB",
		"states":[
			"Saint John",
			"Saint George",
			"Christ Church",
			"Saint Peter",
			"Saint Thomas",
			"Saint Joseph",
			"Saint Andrew",
			"Saint Philip",
			"Saint James",
			"Saint Lucy",
			"Saint Michael"
		]
	},
	{
		"name":"Belarus",
		"iso2":"BY",
		"states":[
			"Mahilyowskaya Voblasts",
			"Minskaja Voblasts\\'",
			"Homjel\\'",
			"Hrodna",
			"Minsk",
			"Brest",
			"Vicebsk",
			"Mahiljow",
			"Petrik"
		]
	},
	{
		"name":"Belgium",
		"iso2":"BE",
		"states":[
			"Antwerpen",
			"Liege",
			"Namur",
			"Brussel",
			"Brabant Wallon",
			"Berchem",
			"West-Vlaanderen",
			"Luxembourg",
			"Brabant",
			"Hainaut",
			"Limburg",
			"Provincie Brabant",
			"Oost-Vlaanderen",
			"East Flanders",
			"Ontario",
			"Wallonne",
			"Vlaams-Brabant"
		]
	},
	{
		"name":"Belize",
		"iso2":"BZ",
		"states":[
			"Corozal",
			"Cayo",
			"Orange Walk",
			"Toledo",
			"Belize",
			"Stann Creek"
		]
	},
	{
		"name":"Benin",
		"iso2":"BJ",
		"states":[
			"Borgou",
			"Collines",
			"Mono",
			"Donga",
			"Atlantique",
			"Couffo",
			"Plateau",
			"Littoral",
			"Alibori",
			"Atacora",
			"Oueme",
			"Zou"
		]
	},
	{
		"name":"Bermuda",
		"iso2":"BM",
		"states":[
			"Hamilton",
			"Saint George"
		]
	},
	{
		"name":"Bhutan",
		"iso2":"BT",
		"states":[
			"Chhukha",
			"Chirang",
			"Samchi",
			"Daga",
			"Tashigang",
			"Punakha",
			"Rinpung",
			"Geylegphug",
			"Samdrup Jongkhar",
			"Tongsa",
			"Lhuntshi",
			"Wangdiphodrang",
			"Shemgang",
			"Bumthang",
			"Pemagatsel",
			"Ha",
			"Timphu",
			"Mongar"
		]
	},
	{
		"name":"Bolivia",
		"iso2":"BO",
		"states":[
			"Potosi",
			"Cochabamba",
			"Tarija",
			"Santa Cruz",
			"Pando",
			"Oruro",
			"Chuquisaca",
			"Beni",
			"La Paz"
		]
	},
	{
		"name":"Bosnia and Herzegovina",
		"iso2":"BA",
		"states":[
			"Federacija Bosna i Hercegovina",
			"Republika Srpska"
		]
	},
	{
		"name":"Botswana",
		"iso2":"BW",
		"states":[
			"Central Tutume",
			"Jwaneng",
			"North East",
			"Central Mahalapye",
			"Kgalagadi South",
			"Lobatse",
			"Orapa",
			"Kgalagadi North",
			"Okavango",
			"South East",
			"Chobe",
			"Central Serowe-Palapye",
			"Ngamiland",
			"Central Bobonong",
			"Francistown",
			"Gaborone",
			"Ngwaketse",
			"Ghanzi",
			"Selibe Phikwe",
			"Central Boteti",
			"Kgatleng",
			"Kweneng",
			"Sowa"
		]
	},
	{
		"name":"Bouvet Island",
		"iso2":"BV",
		"states":[
			"Bouvet Island"
		]
	},
	{
		"name":"Brazil",
		"iso2":"BR",
		"states":[
			"Rio Grande do Norte",
			"Tocantins",
			"Paraiba",
			"Rio de Janeiro",
			"Mato Grosso do Sul",
			"Acre",
			"Pernambuco",
			"Espirito Santo",
			"Sao Paulo",
			"Mato Grosso",
			"Para",
			"Alagoas",
			"Ceara",
			"Sergipe",
			"Amapa",
			"Rio Grande do Sul",
			"Rondonia",
			"Amazonas",
			"Piaui",
			"Santa Catarina",
			"Distrito Federal",
			"Bahia",
			"Maranhao",
			"Goias",
			"Minas Gerais",
			"Roraima",
			"Estado de Sao Paulo",
			"Parana"
		]
	},
	{
		"name":"British Indian Ocean Territory",
		"iso2":"IO",
		"states":[
			"British Indian Ocean Territory"
		]
	},
	{
		"name":"Brunei",
		"iso2":"BN",
		"states":[]
	},
	{
		"name":"Bulgaria",
		"iso2":"BG",
		"states":[
			"Sliven",
			"Haskovo",
			"Oblast Sofiya-Grad",
			"Blagoevgrad",
			"Sofijska oblast",
			"Burgas",
			"Sofija grad",
			"Gabrovo",
			"Dobrich",
			"Razgrad",
			"Veliko Tarnovo",
			"Pazardzhik",
			"Silistra",
			"Targovishte",
			"Montana",
			"Pleven",
			"Shumen",
			"Yablaniza",
			"Ruse",
			"Varna",
			"Smoljan",
			"Plovdiv",
			"Jambol",
			"Lovech",
			"Kardzhali",
			"Stara Zagora",
			"Vraca",
			"Kjustendil",
			"Vidin",
			"Pernik"
		]
	},
	{
		"name":"Burkina Faso",
		"iso2":"BF",
		"states":[
			"Bougouriba",
			"Komandjari",
			"Seno",
			"Ganzourgou",
			"Sourou",
			"Mouhoun",
			"Boulkiemde",
			"Kossi",
			"Bazega",
			"Tuy",
			"Boulgou",
			"Bale",
			"Sanguie",
			"Noumbiel",
			"Nahouri",
			"Leraba",
			"Kadiogo",
			"Kouritenga",
			"Kourweogo",
			"Sissili",
			"Sanmatenga",
			"Yatenga",
			"Soum",
			"Houet",
			"Namentenga",
			"Oudalan",
			"Passore",
			"Bam",
			"Ioba",
			"Zoundweogo",
			"Gnagna",
			"Gourma",
			"Oubritenga",
			"Kenedougou",
			"Poni",
			"Comoe",
			"Kompienga",
			"Zondoma",
			"Tapoa"
		]
	},
	{
		"name":"Burundi",
		"iso2":"BI",
		"states":[
			"Rutana",
			"Bururi",
			"Bubanza",
			"Muramvya",
			"Ruyigi",
			"Kayanza",
			"Bujumbura",
			"Cibitoke",
			"Kirundo",
			"Karuzi",
			"Makamba",
			"Cankuzo",
			"Muyinga",
			"Ngozi",
			"Gitega"
		]
	},
	{
		"name":"Cambodia",
		"iso2":"KH",
		"states":[
			"Banteay Mean Chey",
			"Krong Pailin",
			"Kandal",
			"Pousat",
			"Prey Veaeng",
			"Kracheh",
			"Kampong Thum",
			"Kampong Spoeu",
			"Rotanak Kiri",
			"Stueng Traeng",
			"Bat Dambang",
			"Kaoh Kong",
			"Otdar Mean Chey",
			"Mondol Kiri",
			"Kampong Chhnang",
			"Phnum Penh",
			"Krong Kaeb",
			"Kampot",
			"Kampong Cham",
			"Krong Preah Sihanouk",
			"Siem Reab",
			"Takaev",
			"Svay Rieng",
			"Preah Vihear"
		]
	},
	{
		"name":"Cameroon",
		"iso2":"CM",
		"states":[
			"Sudouest",
			"Est",
			"Nordouest",
			"Centre",
			"Ouest",
			"Adamaoua",
			"Sud",
			"Nord",
			"Littoral",
			"Nord Extreme"
		]
	},
	{
		"name":"Canada",
		"iso2":"CA",
		"states":[
			"British Columbia",
			"Newfoundland and Labrador",
			"Saskatchewan",
			"Prince Edward Island",
			"Ontario",
			"Nova Scotia",
			"Quebec",
			"Alberta",
			"Manitoba",
			"Northwest Territories",
			"New Brunswick",
			"Nunavut",
			"Yukon"
		]
	},
	{
		"name":"Cape Verde",
		"iso2":"CV",
		"states":[
			"Santo Antao",
			"Sao Tiago",
			"Boavista",
			"Sal",
			"Sao Nicolau",
			"Brava",
			"Sao Vicente",
			"Maio",
			"Fogo"
		]
	},
	{
		"name":"Cayman Islands",
		"iso2":"KY",
		"states":[
			"Grand Cayman"
		]
	},
	{
		"name":"Central African Republic",
		"iso2":"CF",
		"states":[
			"Lobaye",
			"Haut-Mbomou",
			"Mbomou",
			"Basse-Kotto",
			"Kemo",
			"Bangui",
			"Mambere-Kadei",
			"Haute-Kotto",
			"Vakaga",
			"Ouham-Pende",
			"Ouham",
			"Nana-Mambere",
			"Bamingui-Bangoran",
			"Ouaka",
			"Sangha-Mbaere",
			"Nana-Gribizi",
			"Ombella Mpoko"
		]
	},
	{
		"name":"Chad",
		"iso2":"TD",
		"states":[
			"Chari-Baguirmi",
			"Moyen-Chari",
			"Batha",
			"Bourkou-Ennedi-Tibesti",
			"Logone Occidental",
			"Salamat",
			"Lac",
			"Ouaddai",
			"Guera",
			"Tandjile",
			"Biltine",
			"Logone Oriental",
			"Mayo-Kebbi",
			"Kanem"
		]
	},
	{
		"name":"Chile",
		"iso2":"CL",
		"states":[
			"Magellanes",
			"Tarapaca",
			"Coquimbo",
			"Metropolitana",
			"Antofagasta",
			"Maule",
			"Valparaiso",
			"Aisen",
			"Los Lagos",
			"Libertador General Bernardo O\\'",
			"Bio Bio",
			"Metropolitana de Santiago",
			"Araucania",
			"Atacama"
		]
	},
	{
		"name":"China",
		"iso2":"CN",
		"states":[
			"Anhui",
			"Tianjin",
			"Shanghai",
			"Anhui Sheng",
			"Xizang",
			"Fujian Sheng",
			"Guangdong Sheng",
			"Gansu",
			"Hebei",
			"Hainan",
			"Yunnan",
			"Hubei",
			"Zhejiang",
			"Liaoning Sheng",
			"Beijing Shi",
			"Heilongjiang",
			"Jiangxi",
			"Anhui Province",
			"Nei Monggol",
			"Chongqing",
			"Xinjiang",
			"Shaanxi",
			"Jiangsu",
			"Zhejiang Sheng",
			"Henan",
			"Shanxi",
			"Guizhou",
			"Fujian",
			"Beijing",
			"Shandong",
			"Hunan",
			"Guangxi",
			"Shandong Sheng",
			"Xianggang",
			"Qinghai",
			"Jiangsu Sheng",
			"Sichuan",
			"Aomen",
			"Liaoning",
			"Guangdong",
			"Jilin",
			"Ningxia Hui"
		]
	},
	{
		"name":"Christmas Island",
		"iso2":"CX",
		"states":[
			"Christmas Island"
		]
	},
	{
		"name":"Cocos (Keeling) Islands",
		"iso2":"CC",
		"states":[
			"Cocos (Keeling) Islands"
		]
	},
	{
		"name":"Colombia",
		"iso2":"CO",
		"states":[
			"Santander",
			"Caqueta",
			"Bolivar",
			"Quindio",
			"Guaviare",
			"Cundinamarca",
			"Cordoba",
			"Cauca",
			"Vichada",
			"Tolima",
			"La Guajira",
			"Meta",
			"Arauca",
			"Amazonas",
			"Caldas",
			"Atlantico",
			"Sucre",
			"Huila",
			"Putumayo",
			"Vaupes",
			"Valle del Cauca",
			"Magdalena",
			"Norte de Santander",
			"Risaralda",
			"Boyaca",
			"Antioquia",
			"Bogota",
			"Guainia",
			"San Andres y Providencia",
			"Narino",
			"Casanare",
			"Cesar",
			"Choco"
		]
	},
	{
		"name":"Comoros",
		"iso2":"KM",
		"states":[
			"Mwali",
			"Njazidja",
			"Nzwani"
		]
	},
	{
		"name":"Congo",
		"iso2":"CG",
		"states":[
			"Sangha",
			"Plateaux",
			"Cuvette",
			"Kouilou",
			"Brazzaville",
			"Niari",
			"Lekoumou",
			"Likouala",
			"Pool",
			"Bouenza"
		]
	},
	{
		"name":"Congo The Democratic Republic Of The",
		"iso2":"CD",
		"states":[]
	},
	{
		"name":"Cook Islands",
		"iso2":"CK",
		"states":[
			"Manihiki",
			"Mangaia",
			"Mitiaro",
			"Tongareva",
			"Rarotonga",
			"Aitutaki",
			"Atiu",
			"Pukapuka",
			"Nassau",
			"Mauke",
			"Rakahanga"
		]
	},
	{
		"name":"Costa Rica",
		"iso2":"CR",
		"states":[
			"Alajuela",
			"Cartago",
			"San Jose",
			"Puntarenas",
			"Heredia",
			"Limon",
			"Guanacaste"
		]
	},
	{
		"name":"Cote D'Ivoire (Ivory Coast)",
		"iso2":"CI",
		"states":[]
	},
	{
		"name":"Croatia (Hrvatska)",
		"iso2":"HR",
		"states":[]
	},
	{
		"name":"Cuba",
		"iso2":"CU",
		"states":[
			"Villa Clara",
			"La Habana",
			"Habana",
			"Sancti Spiritus",
			"Isla de la Juventud",
			"Cienfuegos",
			"Matanzas",
			"Pinar del Rio",
			"Ciego de Avila",
			"Las Tunas",
			"Granma",
			"Holguin",
			"Camaguey",
			"Guantanamo",
			"Santiago de Cuba",
			"Ciudad de la Habana"
		]
	},
	{
		"name":"Cyprus",
		"iso2":"CY",
		"states":[
			"Limassol",
			"Nicosia District",
			"Turkish controlled area",
			"Government controlled area",
			"Paphos"
		]
	},
	{
		"name":"Czech Republic",
		"iso2":"CZ",
		"states":[
			"Rajhrad",
			"South Moravian",
			"Karlovarsky",
			"Jihocesky Kraj",
			"Jihomoravsky",
			"Moravskoslezsky",
			"Kralovehradecky",
			"Valletta",
			"Zlinsky",
			"Jihochesky",
			"Central Bohemian",
			"Ustecky",
			"Unicov",
			"Lipov",
			"Stredochesky",
			"Liberecky",
			"Olomoucky",
			"Straz nad Nisou",
			"Plzensky",
			"Velesin",
			"Pardubicky",
			"Klecany",
			"Praha",
			"Frycovice",
			"Vysochina",
			"Smirice",
			"Olomoucky Kraj"
		]
	},
	{
		"name":"Denmark",
		"iso2":"DK",
		"states":[
			"Nordjylland",
			"Ringkobing",
			"Soeborg",
			"Roslev",
			"Syddanmark",
			"Kobenhavns Amt",
			"Fyn",
			"Roskilde",
			"Bornholm",
			"Arhus",
			"Hovedstaden",
			"Viborg",
			"Kobenhavns Kommune",
			"Storstrom",
			"Vestsjalland",
			"Frederiksborg",
			"Roervig",
			"Ribe",
			"Toelloese",
			"Kobenhavn",
			"Vejle",
			"Sonderjylland",
			"Sjaelland"
		]
	},
	{
		"name":"Djibouti",
		"iso2":"DJ",
		"states":[
			"Tajurah",
			"Ubuk",
			"Jibuti",
			"\\'Ali Sabih",
			"Dikhil"
		]
	},
	{
		"name":"Dominica",
		"iso2":"DM",
		"states":[
			"Saint John",
			"Saint Mark",
			"Saint George",
			"Saint Patrick",
			"Saint Paul",
			"Saint Luke",
			"Saint David",
			"Saint Joseph",
			"Saint Peter",
			"Saint Andrew"
		]
	},
	{
		"name":"Dominican Republic",
		"iso2":"DO",
		"states":[
			"San Juan",
			"Distrito Nacional",
			"Espaillat",
			"Bahoruco",
			"San Pedro de Macoris",
			"La Altagracia",
			"Santiago",
			"Duarte",
			"Maria Trinidad Sanchez",
			"Valverde",
			"Samana",
			"La Romana",
			"Monte Cristi",
			"Dajabon",
			"Pedernales",
			"Independencia",
			"Monte Plata",
			"El Seybo",
			"Monsenor Nouel",
			"Barahona",
			"Sanchez Ramirez",
			"San Cristobal",
			"La Vega",
			"Salcedo",
			"Santiago Rodriguez",
			"Peravia",
			"Hato Mayor",
			"Puerto Plata",
			"Elias Pina",
			"Azua"
		]
	},
	{
		"name":"East Timor",
		"iso2":"TL",
		"states":[
			"Ambeno",
			"Dili",
			"Viqueque",
			"Manufahi",
			"Aileu",
			"Ainaro",
			"Baucau",
			"Bobonaro",
			"Liquica",
			"Cova Lima",
			"Lautem",
			"Ermera",
			"Manatuto"
		]
	},
	{
		"name":"Ecuador",
		"iso2":"EC",
		"states":[
			"Pastaza",
			"Loja",
			"Pichincha",
			"Bolivar",
			"Guayas",
			"Morona Santiago",
			"Los Rios",
			"Napo",
			"Imbabura",
			"Canar",
			"Zamora Chinchipe",
			"Carchi",
			"Orellana",
			"Chimborazo",
			"Manabi",
			"El Oro",
			"Galapagos",
			"Cotopaxi",
			"Azuay",
			"Esmeraldas",
			"Sucumbios",
			"Tungurahua"
		]
	},
	{
		"name":"Egypt",
		"iso2":"EG",
		"states":[
			"al-Qalyubiyah",
			"Muhafazat al Fayyum",
			"as-Suways",
			"Aswan",
			"al-Iskandariyah",
			"Sina ash-Shamaliyah",
			"ad-Daqahliyah",
			"Asyut",
			"Muhafazat al Qahirah",
			"ash-Sharqiyah",
			"Matruh",
			"al-Minya",
			"al-Buhayrah",
			"Kafr-ash-Shaykh",
			"al-Uqsur",
			"Sina al-Janubiyah",
			"Qina",
			"Bani Suwayf",
			"Muhafazat al Iskandariyah",
			"Bur Sa\\'id",
			"Dumyat",
			"al-Jizah",
			"Muhafazat al Gharbiyah",
			"al-Fayyum",
			"al-Gharbiyah",
			"al-Qahira",
			"al-Minufiyah",
			"Muhafazat ad Daqahliyah",
			"al-Wadi al-Jadid",
			"al-Bahr-al-Ahmar",
			"al-Ismailiyah",
			"Sawhaj",
			"Cairo"
		]
	},
	{
		"name":"El Salvador",
		"iso2":"SV",
		"states":[
			"San Miguel",
			"La Libertad",
			"Chalatenango",
			"San Salvador",
			"Cabanas",
			"Usulutan",
			"Santa Ana",
			"San Vicente",
			"Morazan",
			"Cuscatlan",
			"Ahuachapan",
			"Sonsonate",
			"La Union",
			"La Paz"
		]
	},
	{
		"name":"Equatorial Guinea",
		"iso2":"GQ",
		"states":[
			"Centro Sur",
			"Kie-Ntem",
			"Wele-Nzas",
			"Annobon",
			"Bioko Sur",
			"Litoral",
			"Bioko Norte"
		]
	},
	{
		"name":"Eritrea",
		"iso2":"ER",
		"states":[
			"Maekel",
			"Gash-Barka",
			"Debub-Keih-Bahri",
			"Semien-Keih-Bahri",
			"Anseba",
			"Debub"
		]
	},
	{
		"name":"Estonia",
		"iso2":"EE",
		"states":[
			"Tartu",
			"Ida-Viru",
			"Polva",
			"Laane",
			"Voru",
			"Jogeva",
			"Viljandi",
			"Harju",
			"Jarva",
			"Parnu",
			"Laane-Viru",
			"Saare",
			"Valga",
			"Rapla",
			"Hiiu"
		]
	},
	{
		"name":"Ethiopia",
		"iso2":"ET",
		"states":[
			"Jigjiga",
			"Addis Abeba",
			"Harar",
			"Southern",
			"Tigray",
			"Oromia",
			"Amhara",
			"Benishangul",
			"Somali",
			"Gambella",
			"Afar",
			"Mekele",
			"Diredawa"
		]
	},
	{
		"name":"Falkland Islands",
		"iso2":"FK",
		"states":[
			"Falkland Islands",
			"South Georgia"
		]
	},
	{
		"name":"Faroe Islands",
		"iso2":"FO",
		"states":[
			"Nor oy",
			"Torshavn",
			"Vaga",
			"Su uroy",
			"Nor ara Eysturoy",
			"Streymoy",
			"Sandoy",
			"Sy ra Eysturoy",
			"Klaksvik"
		]
	},
	{
		"name":"Fiji Islands",
		"iso2":"FJ",
		"states":[
			"South Pacific",
			"Central",
			"Western",
			"Northern",
			"Eastern"
		]
	},
	{
		"name":"Finland",
		"iso2":"FI",
		"states":[
			"Etela-Suomen Laani",
			"Lappi",
			"Lansi-Suomen Laani",
			"Ita-Uusimaa",
			"Saarijarvi",
			"Etela-Karjala",
			"Pirkanmaa",
			"Pohjanmaa",
			"Uleaborgs Lan",
			"Kainuu",
			"Oulun Laani",
			"Ita-Suomen Laani",
			"Pohjois-Pohjanmaa",
			"Etela-Pohjanmaa",
			"Kymenlaakso",
			"Pohjois-Karjala",
			"Keski-Pohjanmaa",
			"Keski-Suomi",
			"Tavastia Proper",
			"Kanta-Hame",
			"Uusimaa",
			"Paijat-Hame",
			"Northern Savonia",
			"Ahvenanmaa",
			"Satakunta",
			"Ostrobothnia",
			"Etela-Savo",
			"Varsinais-Suomi",
			"Pohjois-Savo",
			"Southern Savonia"
		]
	},
	{
		"name":"France",
		"iso2":"FR",
		"states":[
			"Hautes-Alpes",
			"Tarn",
			"Languedoc-Roussillon",
			"Paris",
			"Lower Normandy",
			"Corse-du-Sud",
			"Burgundy",
			"Doubs",
			"Calvados",
			"Var",
			"Haut-Rhin",
			"Meurthe-et-Moselle",
			"Haute-Marne",
			"Moselle",
			"Bretagne",
			"Le Creusot",
			"Gironde",
			"Haute-Loire",
			"Cedex",
			"Eure",
			"Jura",
			"Herault",
			"Loir-et-Cher",
			"Quelmes",
			"Klagenfurt",
			"Brittany",
			"Ain",
			"Seine-et-Marne",
			"Vellise",
			"Yonne",
			"Crolles",
			"Mayenne",
			"Val-de-Marne",
			"Alpes-Maritimes",
			"Finistere",
			"Lozere",
			"Gard",
			"Morbihan",
			"Haute-Vienne",
			"Cotes-d\\'Armor",
			"Haute-Corse",
			"Rhone-Alpes",
			"Basse-Normandie",
			"Loire-Atlantique",
			"Creuse",
			"Oise",
			"Lot-et-Garonne",
			"Cantal",
			"Ile-de-France",
			"Yvelines",
			"Bourgogne",
			"Rhone",
			"Meuse",
			"Orne",
			"Indre-et-Loire",
			"Maine-et-Loire",
			"Vaucluse",
			"Savoie",
			"Bouches-du-Rhone",
			"Upper Normandy",
			"Limousin",
			"Hautes-Pyrenees",
			"Loire",
			"Haute-Saone",
			"Pyrenees-Atlantiques",
			"Le Castellet",
			"Essonne",
			"Indre",
			"Alpes-Cote dAzur",
			"Ariege",
			"Aude",
			"Val-d\\'Oise",
			"Deux-Sevres",
			"Eure-et-Loir",
			"Vendee",
			"Saint Ouen",
			"Hauts-de-Seine",
			"Lorraine",
			"Picardy",
			"Pyrenees-Orientales",
			"Lot",
			"Alpes-de-Haute-Provence",
			"Charente",
			"Aquitaine",
			"Loiret",
			"Manche",
			"Pays-de-la-Loire",
			"Centre",
			"Larcay",
			"Saone-et-Loire",
			"Ille-et-Vilaine",
			"Midi-Pyrenees",
			"Correze",
			"Franche-Comte",
			"Vosges",
			"Marne",
			"Isere",
			"Pays de la Loire",
			"Nievre",
			"Aube",
			"Sarthe",
			"Tarn-et-Garonne",
			"Albi Le Sequestre",
			"Aisne",
			"Saint Viatre",
			"Haute-Savoie",
			"Cote-d\\'Or",
			"Haute-Garonne",
			"Gers",
			"Drome",
			"Nord",
			"Allier",
			"Charente-Maritime",
			"Vienne",
			"Landes",
			"Pas-de-Calais",
			"Auvergne",
			"Alsace",
			"Aveyron",
			"Somme",
			"Seine-Saint-Denis",
			"Souvans",
			"Seine-Maritime",
			"Dordogne",
			"Nord-Pas-de-Calais",
			"Puy-de-Dome",
			"Feucherolles",
			"Sophia Antipolis",
			"Ardennes",
			"Ardeche",
			"Cher",
			"Treignac",
			"Bas-Rhin",
			"Territoire de Belfort"
		]
	},
	{
		"name":"French Guiana",
		"iso2":"GF",
		"states":[
			"Cayenne",
			"Saint-Laurent-du-Maroni"
		]
	},
	{
		"name":"French Polynesia",
		"iso2":"PF",
		"states":[
			"Tuamotu",
			"Iles du Vent",
			"Marquesas",
			"Iles sous le Vent",
			"Tubuai"
		]
	},
	{
		"name":"French Southern Territories",
		"iso2":"TF",
		"states":[
			"Amsterdam",
			"Kerguelen",
			"Crozet Islands"
		]
	},
	{
		"name":"Gabon",
		"iso2":"GA",
		"states":[
			"Moyen-Ogooue",
			"Ogooue-Lolo",
			"Haut-Ogooue",
			"Woleu-Ntem",
			"Estuaire",
			"Ogooue-Ivindo",
			"Ogooue-Maritime",
			"Ngounie",
			"Nyanga"
		]
	},
	{
		"name":"Gambia The",
		"iso2":"GM",
		"states":[
			"Basse",
			"Banjul",
			"Brikama",
			"Kanifing",
			"Kerewan",
			"Janjanbureh",
			"Mansakonko",
			"Kuntaur"
		]
	},
	{
		"name":"Georgia",
		"iso2":"GE",
		"states":[
			"Samagrelo-Zemo Svaneti",
			"Imereti",
			"Samche-Zhavaheti",
			"Kaheti",
			"Racha",
			"Mcheta-Mtianeti",
			"Ajaria",
			"Kvemo Kartli",
			"Abhasia",
			"Guria",
			"Shida Kartli",
			"Tbilisi"
		]
	},
	{
		"name":"Germany",
		"iso2":"DE",
		"states":[
			"schlobborn",
			"Bavaria",
			"Saxony",
			"Schleswig-Holstein",
			"Weinstrabe",
			"Brandenburg",
			"Bremen",
			"Rhineland-Palatinate",
			"Land Hessen",
			"Thuringia",
			"Osterode",
			"Neubeuern",
			"Webling",
			"Land Sachsen",
			"Mecklenburg-Vorpommern",
			"Rheinland-Pfalz",
			"Noord-Holland",
			"Laasdorf",
			"Munich",
			"Land Thuringen",
			"Berlin",
			"Auvergne",
			"Hamburg",
			"Land Baden-Wurttemberg",
			"Bayern",
			"Sachsen-Anhalt",
			"Hannover",
			"Nordrhein-Westfalen",
			"Baden-Wurttemberg",
			"Saarland",
			"Land Sachsen-Anhalt",
			"Mulfingen",
			"Dreisbach",
			"Land Mecklenburg-Vorpommern",
			"Sachsen",
			"Land Brandenburg",
			"Hessen",
			"North Rhine-Westphalia",
			"Lower Saxony",
			"Freistaat Bayern",
			"Niedersachsen",
			"Land Nordrhein-Westfalen",
			"Heroldstatt",
			"Land Bayern",
			"Beilstein Wurtt",
			"Land Rheinland-Pfalz",
			"Kortenberg"
		]
	},
	{
		"name":"Ghana",
		"iso2":"GH",
		"states":[
			"Upper East",
			"Brong-Ahafo",
			"Central",
			"Northern",
			"Eastern",
			"Upper West",
			"Ashanti",
			"Greater Accra",
			"Western",
			"Volta"
		]
	},
	{
		"name":"Gibraltar",
		"iso2":"GI",
		"states":[
			"Gibraltar"
		]
	},
	{
		"name":"Greece",
		"iso2":"GR",
		"states":[
			"Attiki",
			"Fokis",
			"Ilia",
			"West Greece",
			"Rethimni",
			"Grevena",
			"Kavala",
			"Heraklion",
			"Ayion Oros",
			"Evritania",
			"Dodekanisos",
			"Kerkira",
			"Hios",
			"Hania",
			"Kilkis",
			"Evros",
			"Pella",
			"Ioannina",
			"Lesvos",
			"Evia",
			"Preveza",
			"Fthiotis",
			"Xanthi",
			"Kefallinia",
			"Kozani",
			"Imathia",
			"Rodopi",
			"Thessaloniki",
			"Levkas",
			"Aitolia kai Akarnania",
			"Kiklades",
			"Serrai",
			"Iraklion",
			"Kastoria",
			"Halandri",
			"Trikala",
			"Thesprotia",
			"Drama",
			"Halkidiki",
			"Voiotia",
			"Argolis",
			"Zakinthos",
			"Pieria",
			"Arkadia",
			"Larisa",
			"Messinia",
			"Attica",
			"Arta",
			"Nomos Zakynthou",
			"Evvoia",
			"Acharnes",
			"Korinthia",
			"Karditsa",
			"Florina",
			"Lasithi",
			"Lakonia",
			"Magnisia",
			"Nomos Attikis",
			"Samos",
			"Crete",
			"Piraios",
			"Ahaia"
		]
	},
	{
		"name":"Greenland",
		"iso2":"GL",
		"states":[
			"Kangaatsiaq",
			"Sisimiut",
			"Illoqqortoormiut",
			"Qeqertarsuaq",
			"Qaanaaq",
			"Ilulissat",
			"Narsaq",
			"Aasiaat",
			"Udenfor kommunal inddeling",
			"Upernavik",
			"Uummannaq",
			"Qaqortoq",
			"Maniitsoq",
			"Nanortalik",
			"Nuuk",
			"Ivittuut",
			"Ammassalik",
			"Qasigiannguit",
			"Paamiut"
		]
	},
	{
		"name":"Grenada",
		"iso2":"GD",
		"states":[
			"Saint John",
			"Saint Mark",
			"Saint Patrick",
			"Saint Davids",
			"Saint Andrew",
			"Carriacou-Petite Martinique",
			"Saint George\\'s"
		]
	},
	{
		"name":"Guadeloupe",
		"iso2":"GP",
		"states":[
			"Saint Martin",
			"Marie-Galante",
			"La Desirade",
			"Iles des Saintes",
			"Basse-Terre",
			"Saint Barthelemy",
			"Grande-Terre"
		]
	},
	{
		"name":"Guam",
		"iso2":"GU",
		"states":[
			"Inarajan",
			"Chalan-Pago-Ordot",
			"Talofofo",
			"Mongmong-Toto-Maite",
			"Merizo",
			"Yigo",
			"Agana Heights",
			"Barrigada",
			"Dededo",
			"Sinajana",
			"Agat",
			"Mangilao",
			"Tamuning",
			"Hagatna",
			"Santa Rita",
			"Yona"
		]
	},
	{
		"name":"Guatemala",
		"iso2":"GT",
		"states":[
			"Santa Rosa",
			"Quezaltenango",
			"Alta Verapaz",
			"Guatemala",
			"Zacapa",
			"Jalapa",
			"Suchitepequez",
			"Quiche",
			"El Progreso",
			"Huehuetenango",
			"Izabal",
			"Jutiapa",
			"Chimaltenango",
			"Chiquimula",
			"Sacatepequez",
			"Retalhuleu",
			"Peten",
			"Solola",
			"Totonicapan",
			"San Marcos",
			"Baja Verapaz",
			"Escuintla"
		]
	},
	{
		"name":"Guernsey and Alderney",
		"iso2":"GG",
		"states":[
			"Saint Martin",
			"Sark",
			"Saint Sampson",
			"Castel",
			"Saint Peter Port",
			"Vale",
			"Saint Saviour",
			"Saint Pierre du Bois",
			"Forest",
			"Saint Andrew",
			"Alderney",
			"Torteval"
		]
	},
	{
		"name":"Guinea",
		"iso2":"GN",
		"states":[
			"Lola",
			"Gaoual",
			"Gueckedou",
			"Boke",
			"Kerouane",
			"Kindia",
			"Tougue",
			"Mandiana",
			"Koubia",
			"Forecariah",
			"Labe",
			"Coyah",
			"Kouroussa",
			"Beyla",
			"Yomou",
			"Boffa",
			"Koundara",
			"Fria",
			"Kissidougou",
			"Mamou",
			"Faranah",
			"Macenta",
			"Mali",
			"Pita",
			"Siguiri",
			"Dalaba",
			"Dabola",
			"Dinguiraye",
			"Kankan",
			"Nzerekore",
			"Conakry",
			"Telimele"
		]
	},
	{
		"name":"Guinea-Bissau",
		"iso2":"GW",
		"states":[
			"Oio",
			"Bolama",
			"Gabu",
			"Bafata",
			"Quinara",
			"Tombali",
			"Cacheu",
			"Bissau"
		]
	},
	{
		"name":"Guyana",
		"iso2":"GY",
		"states":[
			"Essequibo Islands-West Demerar",
			"Upper Demerara-Berbice",
			"Upper Takutu-Upper Essequibo",
			"Barima-Waini",
			"Demerara-Mahaica",
			"Pomeroon-Supenaam",
			"Cuyuni-Mazaruni",
			"East Berbice-Corentyne",
			"Potaro-Siparuni",
			"Mahaica-Berbice"
		]
	},
	{
		"name":"Haiti",
		"iso2":"HT",
		"states":[
			"Sud",
			"Grand\\'Anse",
			"Artibonite",
			"Centre",
			"Sud-Est",
			"Ouest",
			"Nord-Ouest",
			"Nord-Est",
			"Nord"
		]
	},
	{
		"name":"Heard and McDonald Islands",
		"iso2":"HM",
		"states":[
			"Heard and McDonald Islands"
		]
	},
	{
		"name":"Honduras",
		"iso2":"HN",
		"states":[
			"El Paraiso",
			"Gracias a Dios",
			"Olancho",
			"Francisco Morazan",
			"Ocotepeque",
			"Valle",
			"Choluteca",
			"Yoro",
			"La Paz",
			"Lempira",
			"Colon",
			"Cortes",
			"Comayagua",
			"Distrito Central",
			"Islas de la Bahia",
			"Atlantida",
			"Santa Barbara",
			"Copan",
			"Intibuca"
		]
	},
	{
		"name":"Hong Kong S.A.R.",
		"iso2":"HK",
		"states":[
			"Hong Kong"
		]
	},
	{
		"name":"Hungary",
		"iso2":"HU",
		"states":[
			"Jasz-Nagykun-Szolnok",
			"Budapest",
			"Gyor-Moson-Sopron",
			"Heves",
			"Veszprem",
			"Bacs-Kiskun",
			"Csongrad",
			"Baranya",
			"Szabolcs-Szatmar-Bereg",
			"Nograd",
			"Fejer",
			"Komarom-Esztergom",
			"Hajdu-Bihar",
			"Tolna",
			"Vas",
			"Pest",
			"Borsod-Abauj-Zemplen",
			"Somogy",
			"Zala",
			"Bekes"
		]
	},
	{
		"name":"Iceland",
		"iso2":"IS",
		"states":[
			"Gullbringusysla",
			"Nor urland vestra",
			"Su urnes",
			"Austurland",
			"Vestfir ir",
			"Hofu borgarsva i",
			"Nor urland eystra",
			"Su urland",
			"Vesturland"
		]
	},
	{
		"name":"India",
		"iso2":"IN",
		"states":[
			"Pondicherry",
			"Haryana",
			"Punjab",
			"Goa",
			"Chhattisgarh",
			"Kerala",
			"Daman and Diu",
			"Bihar",
			"Tamil Nadu",
			"Chandigarh",
			"Jammu and Kashmir",
			"Dadra and Nagar Haveli",
			"Jharkhand",
			"Meghalaya",
			"Delhi",
			"Assam",
			"Madhya Pradesh",
			"Lakshadweep",
			"Manipur",
			"Rajasthan",
			"Sikkim",
			"West Bengal",
			"Uttarakhand",
			"Andhra Pradesh",
			"Himachal Pradesh",
			"Vaishali",
			"Nagaland",
			"Gujarat",
			"Arunachal Pradesh",
			"Maharashtra",
			"Tripura",
			"Natwar",
			"Telangana",
			"Karnataka",
			"Mizoram",
			"Odisha",
			"Uttar Pradesh",
			"Narora",
			"Andaman and Nicobar Islands"
		]
	},
	{
		"name":"Indonesia",
		"iso2":"ID",
		"states":[
			"Gorontalo",
			"Lampung",
			"Kalimantan Selatan",
			"Riau",
			"Jawa Timur",
			"Kalimantan Timur",
			"Kalimantan Tengah",
			"Jambi",
			"Kalimantan Barat",
			"Kendal",
			"Maluku",
			"Bali",
			"Sulawesi Tengah",
			"Gandaria",
			"Sumatera Barat",
			"Nusa Tenggara Barat",
			"Sumatera Selatan",
			"Jawa Barat",
			"Banten",
			"Bangka-Belitung",
			"Riau Kepulauan",
			"Maluku Utara",
			"Sumatera Utara",
			"Bengkulu",
			"Solo",
			"Jakarta",
			"Papua",
			"Nusa Tenggara Timur",
			"Yogyakarta",
			"Sulawesi Selatan",
			"Jawa Tengah",
			"Aceh",
			"Sulawesi Tenggara",
			"Sulawesi Utara"
		]
	},
	{
		"name":"Iran",
		"iso2":"IR",
		"states":[
			"Markazi",
			"Mazandaran",
			"Ardabil",
			"Khorasan",
			"Kerman",
			"Kohgiluyeh-e Boyerahmad",
			"Zanjan",
			"Esfahan",
			"Kordestan",
			"Bushehr",
			"Ilam",
			"Hormozgan",
			"Kermanshah",
			"Azarbayjan-e Khavari",
			"Fars",
			"Tehran",
			"Sistan-e Baluchestan",
			"Lorestan",
			"Chahar Mahal-e Bakhtiari",
			"Golestan",
			"Semnan",
			"Gilan",
			"Azarbayjan-e Bakhtari",
			"Hamadan",
			"Yazd",
			"Khuzestan",
			"Qazvin",
			"Ostan-e Esfahan",
			"Qom"
		]
	},
	{
		"name":"Iraq",
		"iso2":"IQ",
		"states":[
			"an-Najaf",
			"al-Basrah",
			"al-Muthanna",
			"Ninawa",
			"Dahuk",
			"Diyala",
			"Dhi Qar",
			"Erbil",
			"Babil",
			"Irbil",
			"al-Anbar",
			"as-Sulaymaniyah",
			"Baghdad",
			"at-Ta\\'mim",
			"Wasit",
			"Maysan",
			"al-Qadisiyah",
			"Karbala",
			"Kurdistan",
			"Salah-ad-Din"
		]
	},
	{
		"name":"Ireland",
		"iso2":"IE",
		"states":[
			"Sligo",
			"Cavan",
			"Waterford",
			"Armagh",
			"Leitrim",
			"Kildare",
			"Kerry",
			"Mayo",
			"Loch Garman",
			"Laois",
			"Cork",
			"Roscommon",
			"Monaghan",
			"Louth",
			"Galway",
			"Leinster",
			"Dublin",
			"Tipperary South Riding",
			"Wicklow",
			"Longford",
			"Carlow",
			"Kilkenny",
			"Ulster",
			"Donegal",
			"Clare",
			"Limerick",
			"Westmeath",
			"Meath",
			"Offaly",
			"Tipperary North Riding",
			"Wexford"
		]
	},
	{
		"name":"Israel",
		"iso2":"IL",
		"states":[
			"Beit Hanania",
			"Umm El Fahem",
			"Gaza",
			"Centre",
			"Ben Gurion Airport",
			"Khefa",
			"Qalqilya",
			"Lower Galilee",
			"Jaffa",
			"Yerushalayim",
			"Kiryat Yam",
			"Tsafon",
			"Haifa District",
			"Tel Aviv",
			"Caesarea",
			"Hadaron",
			"Hebron",
			"Hamerkaz",
			"Hazafon",
			"Bethlehem",
			"Talme Elazar",
			"Jerusalem"
		]
	},
	{
		"name":"Italy",
		"iso2":"IT",
		"states":[
			"Molteno",
			"Bologna",
			"Torino",
			"Caserta",
			"Alessandria",
			"Veneto",
			"Ancona",
			"Pavia",
			"Modena",
			"Lodi",
			"Novara",
			"Valle d\\'Aosta",
			"Avellino",
			"Verona",
			"Liguria",
			"Trentino-Alto Adige",
			"Basilicata",
			"Catania",
			"Treviso",
			"Bergamo",
			"Bolzano",
			"Lazio",
			"Pesaro-Urbino",
			"L\\'Aquila",
			"Roma",
			"Brescia",
			"Piacenza",
			"Monza and Brianza",
			"Agrigento",
			"Milan",
			"Vercelli",
			"Taranto",
			"Piemonte",
			"Siena",
			"Piedmont",
			"Toscana",
			"Calabria",
			"Trapani",
			"Montenegro",
			"Sardegna",
			"Teramo",
			"Udine",
			"Verbano-Cusio-Ossola",
			"Reggio Emilia",
			"Lombardia",
			"Frosinone",
			"Marche",
			"Belluno",
			"Pordenone",
			"Viterbo",
			"Gorizia",
			"Puglia",
			"Ferrara",
			"Chieti",
			"Perugia",
			"Bari",
			"Benevento",
			"Pisa",
			"Umbria",
			"Abruzzo",
			"Salerno",
			"Messina",
			"Lecco",
			"Molise",
			"Abruzzi",
			"Lecce",
			"Firenze",
			"Trento",
			"Como",
			"Macerata",
			"South Tyrol",
			"Vicenza",
			"Cartoceto",
			"Potenza",
			"Genoa",
			"Brindisi",
			"Kosovo",
			"Ascoli Piceno",
			"Florence",
			"Asti",
			"Biella",
			"Forli-Cesena ",
			"Savona",
			"Mantova",
			"Naples",
			"Rimini",
			"Cuneo",
			"Cosenza",
			"Sondrio",
			"Padova",
			"Friuli-Venezia Giulia",
			"Cremona",
			"Campania",
			"Sicilia",
			"Lecco Province",
			"Lombardy",
			"Emilia-Romagna",
			"Parma",
			"Varese",
			"Venezia",
			"Sassari",
			"Arezzo"
		]
	},
	{
		"name":"Jamaica",
		"iso2":"JM",
		"states":[
			"Hanover",
			"Saint Catherine",
			"Kingston",
			"Trelawney",
			"Buxoro Viloyati",
			"Saint Andrews",
			"Clarendon",
			"Saint Mary",
			"Saint Elizabeth",
			"Manchester",
			"Westmoreland",
			"Saint Ann",
			"Saint James",
			"Portland",
			"Saint Thomas"
		]
	},
	{
		"name":"Japan",
		"iso2":"JP",
		"states":[
			"Shimane",
			"Wakayama",
			"Yamanashi",
			"Kanagawa",
			"Kagawa",
			"Shizuoka",
			"Ehime",
			"Mie",
			"Kumamoto",
			"Kanto",
			"Aichi",
			"Chiba",
			"Nagasaki",
			"Nara",
			"Shiga",
			"Miyagi",
			"Hyogo",
			"Kyoto",
			"Tokyo",
			"Okinawa",
			"Iwate",
			"Ishikawa",
			"Yamagata",
			"Gumma",
			"Kochi",
			"Fukuoka",
			"Miyazaki",
			"Aomori",
			"Gifu",
			"Tochigi",
			"Nagano",
			"Oita",
			"Toyama",
			"Hiroshima",
			"Niigata",
			"Fukui",
			"Ibaraki",
			"Yamaguchi",
			"Saitama",
			"Saga",
			"Tokushima",
			"Osaka",
			"Okayama",
			"Akita",
			"Fukushima",
			"Kagoshima",
			"Hokkaido",
			"Tottori"
		]
	},
	{
		"name":"Jersey",
		"iso2":"JE",
		"states":[
			"Grouville",
			"Saint John",
			"Saint Lawrence",
			"Saint Martin",
			"Saint Brelade",
			"Saint Saviour",
			"Saint Mary",
			"Saint Peter",
			"Saint Clement",
			"Saint Helier",
			"Trinity"
		]
	},
	{
		"name":"Jordan",
		"iso2":"JO",
		"states":[
			"Madaba",
			"al-Karak",
			"Irbid",
			"\\'Ajlun",
			"Jarash",
			"at-Tafilah",
			"az-Zarqa\\'",
			"Amman",
			"al-Mafraq",
			"Ma\\'an",
			"al-\\'Aqabah",
			"al-Balqa\\'"
		]
	},
	{
		"name":"Kazakhstan",
		"iso2":"KZ",
		"states":[
			"Mankistau",
			"Pavlodar",
			"Almati",
			"Soltustik Kazakstan",
			"Sigis Kazakstan",
			"Ontustik Kazakstan",
			"Akmola",
			"Batis Kazakstan",
			"Akmecet",
			"Taraz",
			"Burlinsky Region",
			"Atirau",
			"Kostanay",
			"Aktobe",
			"Karagandi"
		]
	},
	{
		"name":"Kenya",
		"iso2":"KE",
		"states":[
			"Central",
			"Eastern",
			"Coast",
			"Western",
			"North Eastern",
			"Rift Valley",
			"Nairobi",
			"Nyanza"
		]
	},
	{
		"name":"Kiribati",
		"iso2":"KI",
		"states":[
			"Teraina",
			"Abemana",
			"Tabiteuea North",
			"Makin",
			"Onotoa",
			"Tarawa South",
			"Abaiang",
			"Beru",
			"Tamana",
			"Banaba",
			"Nonouti",
			"Kiritimati",
			"Aranuka",
			"Nikunau",
			"Butaritari",
			"Tabuaeran",
			"Kuria",
			"Phoenix Islands",
			"Tarawa North",
			"Marakei",
			"Arorae",
			"Maiana",
			"Tabiteuea South"
		]
	},
	{
		"name":"Korea North",
		"iso2":"KP",
		"states":[]
	},
	{
		"name":"Korea South",
		"iso2":"KR",
		"states":[
			"Jeonbuk",
			"Kyeongsangnam",
			"Kwangju",
			"Taejon-gwangyoksi",
			"Kyeongsangbuk",
			"Kyonggi-do",
			"Ulsan",
			"Cheju",
			"Chollanam",
			"Gangwon-do",
			"Taegu",
			"Seoul",
			"Kyungbuk-Do",
			"Goyang-si",
			"Kyunggi-Do",
			"Daegu",
			"Sudogwon",
			"Chollabuk",
			"Busan",
			"Gyeonggi-do",
			"gwangyoksi",
			"Pusan",
			"Chungnam",
			"Incheon",
			"Jeju-Si",
			"Chungbuk",
			"Gyeongsang ",
			"Chungcheongnam",
			"Chungcheongbuk",
			"Kangweon",
			"Kyeonggi",
			"Gyeongsangnam-do",
			"Taejeon",
			"Wonju"
		]
	},
	{
		"name":"Kuwait",
		"iso2":"KW",
		"states":[
			"al-Ahmadi",
			"Al Asimah",
			"al-Jahra",
			"Qadesiya",
			"Safat",
			"Hawalli",
			"Salmiya",
			"al-Kuwayt",
			"al-Farwaniyah",
			"Mishref"
		]
	},
	{
		"name":"Kyrgyzstan",
		"iso2":"KG",
		"states":[
			"Jalal-Abad",
			"Issyk-Kul",
			"Talas",
			"Naryn",
			"Chui",
			"Osh",
			"Bishkek",
			"Batken"
		]
	},
	{
		"name":"Laos",
		"iso2":"LA",
		"states":[
			"Viangchan Prefecture",
			"Luang Nam Tha",
			"Luang Prabang",
			"Champasak",
			"Sekong",
			"Bolikhamsay",
			"Savannakhet",
			"Oudomxay",
			"Viangchan Province",
			"Xiang Khuang",
			"Xaignabury",
			"Bokeo",
			"Saravan",
			"Houaphanh",
			"Khammouane",
			"Phongsaly",
			"Attopu"
		]
	},
	{
		"name":"Latvia",
		"iso2":"LV",
		"states":[
			"Balvu",
			"Rezekne",
			"Jelgavas",
			"Valkas",
			"Cesu",
			"Ogres",
			"Madonas",
			"Rigas",
			"Jekabspils",
			"Liepajas",
			"Valmieras",
			"Aizkraukles",
			"Saldus",
			"Talsu",
			"Gulbenes",
			"Aluksnes",
			"Dobeles",
			"Kuldigas",
			"Riga",
			"Tukuma",
			"Limbazhu",
			"Jelgava",
			"Preilu",
			"Daugavpils",
			"Liepaja",
			"Bauskas",
			"Ventspils",
			"Daugavpils City",
			"Rezeknes",
			"Ludzas",
			"Ventspils City",
			"Kraslavas",
			"Jurmala City"
		]
	},
	{
		"name":"Lebanon",
		"iso2":"LB",
		"states":[
			"ash-Shamal",
			"Jabal Lubnan",
			"Mohafazat Mont-Liban",
			"Sidon",
			"al-Janub",
			"al-Biqa",
			"an-Nabatiyah",
			"Mohafazat Liban-Nord",
			"Beirut"
		]
	},
	{
		"name":"Lesotho",
		"iso2":"LS",
		"states":[
			"Mokhotlong",
			"Thaba-Tseka",
			"Leribe",
			"Butha-Buthe",
			"Qacha\\'s Nek",
			"Quthing",
			"Maseru",
			"Mohale\\'s Hoek",
			"Berea",
			"Mafeteng"
		]
	},
	{
		"name":"Liberia",
		"iso2":"LR",
		"states":[
			"Grand Gedeh",
			"Grand Bassa",
			"Maryland and Grand Kru",
			"Margibi",
			"Nimba",
			"Bomi",
			"Rivercess",
			"Montserrado",
			"Grand Cape Mount",
			"Bong",
			"Loffa",
			"Sinoe"
		]
	},
	{
		"name":"Libya",
		"iso2":"LY",
		"states":[
			"Ghadamis",
			"Tarhunah",
			"Sawfajjin",
			"an-Nuqat al-Khams",
			"Tubruq",
			"al-Khums",
			"Zlitan",
			"al-Jabal al Akhdar",
			"al-Kufrah",
			"az-Zawiyah",
			"Tripolitania",
			"al-Fatih",
			"Surt",
			"Banghazi",
			"al-\\'Aziziyah",
			"ash-Shati\\'",
			"Ajdabiya",
			"Yafran",
			"Sabha",
			"Tarabulus",
			"Gharyan",
			"al-Jufrah",
			"Murzuq",
			"Darnah",
			"Misratah"
		]
	},
	{
		"name":"Liechtenstein",
		"iso2":"LI",
		"states":[
			"Schaan",
			"Gamprin",
			"Triesenberg",
			"Balzers",
			"Triesen",
			"Planken",
			"Eschen",
			"Vaduz",
			"Mauren",
			"Schellenberg",
			"Ruggell"
		]
	},
	{
		"name":"Lithuania",
		"iso2":"LT",
		"states":[
			"Panevezhio",
			"Anyksciai",
			"Taurages",
			"Telshiu",
			"Marijampoles",
			"Vilniaus",
			"Alytaus",
			"Panevezys",
			"Shiauliu",
			"Utenos",
			"Kauno",
			"Klaipedos",
			"Telsiai"
		]
	},
	{
		"name":"Luxembourg",
		"iso2":"LU",
		"states":[
			"Clervaux",
			"Mersch",
			"Echternach",
			"Redange",
			"Luxembourg",
			"Capellen",
			"Vianden",
			"Diekirch",
			"Remich",
			"Wiltz",
			"Grevenmacher",
			"Esch-sur-Alzette"
		]
	},
	{
		"name":"Macau S.A.R.",
		"iso2":"MO",
		"states":[
			"Macau"
		]
	},
	{
		"name":"Macedonia",
		"iso2":"MK",
		"states":[
			"Shtip",
			"Delchevo",
			"Kriva Palanka",
			"Debar",
			"Struga",
			"Berovo",
			"Sveti Nikole",
			"Krushevo",
			"Kratovo",
			"Valandovo",
			"Veles",
			"Radovish",
			"Kumanovo",
			"Skopje",
			"Gostivar",
			"Negotino",
			"Kochani",
			"Gevgelija",
			"Bitola",
			"Kavadarci",
			"Vinica",
			"Demir Hisar",
			"Probishtip",
			"Resen",
			"Kichevo",
			"Prilep",
			"Tetovo",
			"Strumica",
			"Brod",
			"Ohrid"
		]
	},
	{
		"name":"Madagascar",
		"iso2":"MG",
		"states":[
			"Mahajanga",
			"Antananarivo",
			"Toliary",
			"Toamasina",
			"Fianarantsoa",
			"Antsiranana"
		]
	},
	{
		"name":"Malawi",
		"iso2":"MW",
		"states":[
			"Mangochi",
			"Thyolo",
			"Nkhotakota",
			"Machinga",
			"Ntchisi",
			"Balaka",
			"Zomba Municipality",
			"Nsanje",
			"Kasungu",
			"Blantyre City",
			"Lilongwe City",
			"Mzuzu City",
			"Salima",
			"Nkhata Bay",
			"Dedza",
			"Mzimba",
			"Chitipa",
			"Rumphi",
			"Chikwawa",
			"Karonga",
			"Mwanza",
			"Mulanje",
			"Mchinji",
			"Ntcheu",
			"Chiradzulu",
			"Phalombe",
			"Dowa"
		]
	},
	{
		"name":"Malaysia",
		"iso2":"MY",
		"states":[
			"Sarawak",
			"Pahang",
			"Negeri Johor",
			"Melaka",
			"Kedah",
			"Selangor",
			"Penang",
			"Sembilan",
			"Negeri Sembilan",
			"Labuan",
			"Kelantan",
			"Johor",
			"Sabah",
			"Pulau Pinang",
			"Terengganu",
			"Kuala Lumpur",
			"Perak",
			"Perlis"
		]
	},
	{
		"name":"Maldives",
		"iso2":"MV",
		"states":[
			"Gaaf Alif",
			"Kaaf",
			"Laam",
			"Ghaviyani",
			"Male",
			"Raa",
			"Haa Dhaal",
			"Faaf",
			"Thaa",
			"Lhaviyani",
			"Shaviyani",
			"Nuun",
			"Haa Alif",
			"Alif Alif",
			"Baa",
			"Gaaf Dhaal",
			"Vaav",
			"Dhaal",
			"Alif Dhaal",
			"Siin",
			"Miim"
		]
	},
	{
		"name":"Mali",
		"iso2":"ML",
		"states":[
			"Koulikoro",
			"Sikasso",
			"Mopti",
			"Tombouctou",
			"Gao",
			"Segou",
			"Kidal",
			"Bamako",
			"Kayes"
		]
	},
	{
		"name":"Malta",
		"iso2":"MT",
		"states":[
			"Outer Harbour",
			"Valletta",
			"Northern",
			"Inner Harbour",
			"Western",
			"Gozo and Comino",
			"South Eastern"
		]
	},
	{
		"name":"Man (Isle of)",
		"iso2":"IM",
		"states":[
			"Onchan",
			"Peel",
			"Castletown",
			"Port Saint Mary",
			"Douglas",
			"Ramsey",
			"Laxey",
			"Port Erin"
		]
	},
	{
		"name":"Marshall Islands",
		"iso2":"MH",
		"states":[
			"Kwajalein",
			"Jabat",
			"Lib",
			"Wotho",
			"Aur",
			"Namorik",
			"Ailinlaplap",
			"Ailuk",
			"Lae",
			"Likiep",
			"Utrik",
			"Wotje",
			"Enewetak",
			"Bikini",
			"Jaluit",
			"Majuro",
			"Ebon",
			"Namu",
			"Arno",
			"Rongelap",
			"Maloelap",
			"Kili",
			"Mejit",
			"Ujae",
			"Mili"
		]
	},
	{
		"name":"Martinique",
		"iso2":"MQ",
		"states":[
			"La Trinite",
			"Saint-Pierre",
			"Le Marin",
			"Fort-de-France"
		]
	},
	{
		"name":"Mauritania",
		"iso2":"MR",
		"states":[
			"Taqant",
			"Inshiri",
			"Assaba",
			"Adrar",
			"Qidimagha",
			"Nawakshut",
			"Trarza",
			"Tiris Zammur",
			"Dhakhlat Nawadibu",
			"Hudh-ash-Sharqi",
			"Hudh-al-Gharbi",
			"Brakna",
			"Qurqul"
		]
	},
	{
		"name":"Mauritius",
		"iso2":"MU",
		"states":[
			"Pamplempousses",
			"Rodrigues",
			"Flacq",
			"Rose Hill",
			"Plaines Wilhelm",
			"Riviere du Rempart",
			"Port Louis",
			"Black River",
			"Grand Port",
			"Eau Coulee",
			"Savanne",
			"Moka",
			"Floreal"
		]
	},
	{
		"name":"Mayotte",
		"iso2":"YT",
		"states":[
			"Mayotte",
			"Pamanzi"
		]
	},
	{
		"name":"Mexico",
		"iso2":"MX",
		"states":[
			"Estado de Mexico",
			"Chihuahua",
			"Guanajuato",
			"Queretaro",
			"Sinaloa",
			"Tamaulipas",
			"Guerrero",
			"Aguascalientes",
			"Nuevo Leon",
			"Tlaxcala",
			"Nayarit",
			"Chiapas",
			"Zacatecas",
			"San Luis Potosi",
			"Baja California",
			"Quintana Roo",
			"Michoacan",
			"Colima",
			"Sonora",
			"Tabasco",
			"Baja California Sur",
			"Puebla",
			"Oaxaca",
			"Jalisco",
			"Distrito Federal",
			"Campeche",
			"Mexico",
			"Durango",
			"Yucatan",
			"Veracruz",
			"Morelos",
			"Hidalgo",
			"Coahuila"
		]
	},
	{
		"name":"Micronesia",
		"iso2":"FM",
		"states":[
			"Pohnpei",
			"Chuuk",
			"Kusaie",
			"Yap"
		]
	},
	{
		"name":"Moldova",
		"iso2":"MD",
		"states":[
			"Transnistria",
			"Ungheni",
			"Orhei",
			"Lapusna",
			"Chisinau Oras",
			"Cahul",
			"Edinet",
			"Gagauzia",
			"Taraclia",
			"Balti",
			"Tighina",
			"Chisinau",
			"Soroca"
		]
	},
	{
		"name":"Monaco",
		"iso2":"MC",
		"states":[
			"La Condamine",
			"Fontvieille",
			"Monte Carlo",
			"Monaco-Ville"
		]
	},
	{
		"name":"Mongolia",
		"iso2":"MN",
		"states":[
			"Dundgovi",
			"Govisumber",
			"Govi-Altaj",
			"Tov",
			"Hentij",
			"Bajanhongor",
			"Ovorhangaj",
			"Zavhan",
			"Hovd",
			"Darhan-Uul",
			"Arhangaj",
			"Hovsgol",
			"Ulaanbaatar",
			"Dornogovi",
			"Dornod",
			"Selenge",
			"Omnogovi",
			"Bajan-Olgij",
			"Suhbaatar",
			"Uvs",
			"Bulgan",
			"Orhon"
		]
	},
	{
		"name":"Montenegro",
		"iso2":"ME",
		"states":[]
	},
	{
		"name":"Montserrat",
		"iso2":"MS",
		"states":[
			"Montserrat"
		]
	},
	{
		"name":"Morocco",
		"iso2":"MA",
		"states":[
			"Souss Massa-Draa",
			"Gharb-Chrarda-Beni Hssen",
			"Oriental",
			"Guelmim",
			"Oujda",
			"Province de Tanger",
			"Rabat-Sale-Zammour-Zaer",
			"Wilaya de Casablanca",
			"Kenitra",
			"Agadir",
			"Meknes-Tafilalet",
			"Tangier-Tetouan",
			"Settat",
			"Casablanca",
			"Chaouia-Ouardigha",
			"Fes-Boulemane",
			"Tadla-Azilal",
			"Marrakech-Tensift-Al Haouz",
			"Doukkala-Abda",
			"Taza-Al Hoceima-Taounate",
			"Sala Al Jadida",
			"Wilaya de Rabat-Sale"
		]
	},
	{
		"name":"Mozambique",
		"iso2":"MZ",
		"states":[
			"Nampula",
			"Maputo Provincia",
			"Sofala",
			"Cabo Delgado",
			"Maputo",
			"Niassa",
			"Inhambane",
			"Gaza",
			"Zambezia",
			"Manica",
			"Tete"
		]
	},
	{
		"name":"Myanmar",
		"iso2":"MM",
		"states":[
			"Yangon",
			"Mandalay",
			"Tanintharyi",
			"Rakhine",
			"Kayin",
			"Nay Pyi Taw",
			"Ayeyarwady",
			"Kayah",
			"Chin",
			"Mon",
			"Kachin",
			"Magway",
			"Sagaing",
			"Shan",
			"Bago"
		]
	},
	{
		"name":"Namibia",
		"iso2":"NA",
		"states":[
			"Otjozondjupa",
			"Khomas",
			"Oshana",
			"Kunene",
			"Omaheke",
			"Hardap",
			"Karas",
			"Oshikoto",
			"Erongo",
			"Caprivi",
			"Ohangwena",
			"Kavango",
			"Omusati"
		]
	},
	{
		"name":"Nauru",
		"iso2":"NR",
		"states":[
			"Yaren"
		]
	},
	{
		"name":"Nepal",
		"iso2":"NP",
		"states":[
			"Janakpur",
			"Bagmati",
			"Sagarmatha",
			"Gandaki",
			"Koshi",
			"Lumbini",
			"Karnali",
			"Rapti",
			"Seti",
			"Bheri",
			"Narayani",
			"Mechi",
			"Dhawalagiri",
			"Mahakali"
		]
	},
	{
		"name":"Netherlands Antilles",
		"iso2":"AN",
		"states":[
			"Sint Maarten",
			"Bonaire",
			"Curacao",
			"Saba",
			"Sint Eustatius"
		]
	},
	{
		"name":"Netherlands The",
		"iso2":"NL",
		"states":[
			"Groningen",
			"Gelderland",
			"Zeeland",
			"South Holland",
			"Flevoland",
			"Noord-Holland",
			"Friesland",
			"Zuid-Holland",
			"Drenthe",
			"Overijssel",
			"Noord-Brabant",
			"Limburg",
			"Utrecht",
			"Amsterdam",
			"Benelux"
		]
	},
	{
		"name":"New Caledonia",
		"iso2":"NC",
		"states":[
			"Nord",
			"Sud",
			"Iles"
		]
	},
	{
		"name":"New Zealand",
		"iso2":"NZ",
		"states":[
			"Otago",
			"Manawatu-Wanganui",
			"Hawke\\'s Bay",
			"Auckland",
			"Northland",
			"Marlborough",
			"Bay of Plenty",
			"Wellington",
			"Taranaki",
			"Tasman",
			"Waikato",
			"Gisborne",
			"Canterbury",
			"Christchurch",
			"Southland",
			"Area Outside Region",
			"Rodney",
			"West Coast",
			"Nelson"
		]
	},
	{
		"name":"Nicaragua",
		"iso2":"NI",
		"states":[
			"Atlantico Sur",
			"Atlantico Norte",
			"Granada",
			"Esteli",
			"Jinotega",
			"Nueva Segovia",
			"Rio San Juan",
			"Boaco",
			"Leon",
			"Managua",
			"Chinandega",
			"Rivas",
			"Madriz",
			"Chontales",
			"Masaya",
			"Carazo",
			"Matagalpa"
		]
	},
	{
		"name":"Niger",
		"iso2":"NE",
		"states":[
			"Tahoua",
			"Tillabery",
			"Niamey",
			"Zinder",
			"Diffa",
			"Agadez",
			"Maradi",
			"Dosso"
		]
	},
	{
		"name":"Nigeria",
		"iso2":"NG",
		"states":[
			"Kaduna",
			"Ondo",
			"Kogi",
			"Anambra",
			"Imo",
			"Oyo",
			"Plateau",
			"Akwa Ibom",
			"Cross River",
			"Katsina",
			"Gombe",
			"Adamawa",
			"Zamfara",
			"Ogun",
			"Nassarawa",
			"Sokoto",
			"Delta",
			"Kwara",
			"Benue",
			"Jigawa",
			"Yobe",
			"Taraba",
			"Kebbi",
			"Bayelsa",
			"Ekiti",
			"Ebonyi",
			"Enugu",
			"Kano",
			"Abuja Federal Capital Territor",
			"Osun",
			"Bauchi",
			"Edo",
			"Rivers",
			"Lagos",
			"Borno",
			"Niger",
			"Abia"
		]
	},
	{
		"name":"Niue",
		"iso2":"NU",
		"states":[
			"Niue"
		]
	},
	{
		"name":"Norfolk Island",
		"iso2":"NF",
		"states":[
			"Norfolk Island"
		]
	},
	{
		"name":"Northern Mariana Islands",
		"iso2":"MP",
		"states":[
			"Northern Islands",
			"Rota",
			"Saipan",
			"Tinian"
		]
	},
	{
		"name":"Norway",
		"iso2":"NO",
		"states":[
			"Sogn og Fjordane",
			"Oslo",
			"Telemark",
			"Soer Troendelag",
			"Sykkylven",
			"Moere og Romsdal",
			"Finnmark",
			"Vest Agder",
			"Hordaland",
			"Akershus",
			"Hedmark",
			"Oestfold",
			"\u00c3\u0083\u00c2\u0083\u00c3\u0086\u00c2\u0092\u00c3\u0083\u00c2\u0082\u00c3\u008b\u00c2\u009cstfold",
			"Troms",
			"Stavern",
			"Oppland",
			"Nord Trondelag",
			"Aust Agder",
			"Rogaland",
			"Buskerud",
			"Nordland",
			"Vestfold",
			"Bergen"
		]
	},
	{
		"name":"Oman",
		"iso2":"OM",
		"states":[
			"Dhufar",
			"adh-Dhahirah",
			"Wadi Kabir",
			"Al Buraimi",
			"al-Batinah",
			"Musandam",
			"Rusayl",
			"Masqat",
			"ad-Dakhiliyah",
			"ash-Sharqiyah"
		]
	},
	{
		"name":"Pakistan",
		"iso2":"PK",
		"states":[
			"Federal Capital Area",
			"North-West Frontier",
			"Federally administered Tribal ",
			"Northern Areas",
			"Baluchistan",
			"Sind",
			"Punjab"
		]
	},
	{
		"name":"Palau",
		"iso2":"PW",
		"states":[
			"Hatobohei",
			"Airai",
			"Kayangel",
			"Sonsorol",
			"Peleliu",
			"Ngiwal",
			"Melekeok",
			"Koror",
			"Ngaraard",
			"Ngchesar",
			"Ngerchelong",
			"Ngaremlengui",
			"Angaur",
			"Ngardmau",
			"Aimeliik",
			"Ngatpang"
		]
	},
	{
		"name":"Palestinian Territory Occupied",
		"iso2":"PS",
		"states":[
			"Bayt Lahm",
			"Nabulus",
			"al-Quds",
			"Khan Yunis",
			"Ghazzah ash-Shamaliyah",
			"al-Khalil",
			"Ghazzah",
			"Dayr-al-Balah",
			"Qalqilyah",
			"Tubas",
			"Tulkarm",
			"Bethlehem",
			"Ariha",
			"Salfit",
			"Ram Allah wal-Birah",
			"Janin",
			"Rafah"
		]
	},
	{
		"name":"Panama",
		"iso2":"PA",
		"states":[
			"Chiriqui",
			"Kuna Yala",
			"Los Santos",
			"Veraguas",
			"Herrera",
			"Ngobe Bugle",
			"Darien",
			"Bocas del Toro",
			"Colon",
			"Panama",
			"Embera",
			"Cocle"
		]
	},
	{
		"name":"Papua new Guinea",
		"iso2":"PG",
		"states":[
			"East New Britain",
			"Milne Bay",
			"Western Highlands",
			"Gulf",
			"Oro",
			"Enga",
			"Southern Highlands",
			"Sandaun",
			"Morobe",
			"North Solomons",
			"West New Britain",
			"Simbu",
			"Fly River",
			"Manus",
			"New Ireland",
			"East Sepik",
			"Madang",
			"Eastern Highlands",
			"National Capital District"
		]
	},
	{
		"name":"Paraguay",
		"iso2":"PY",
		"states":[
			"Guaira",
			"Central",
			"Alto Parana",
			"Amambay",
			"Concepcion",
			"Presidente Hayes",
			"Paraguari",
			"Canendiyu",
			"Cordillera",
			"Alto Paraguay",
			"Neembucu",
			"Caazapa",
			"Misiones",
			"Caaguazu",
			"Boqueron",
			"Asuncion",
			"Itapua",
			"San Pedro"
		]
	},
	{
		"name":"Peru",
		"iso2":"PE",
		"states":[
			"Pasco",
			"Junin",
			"Loreto",
			"Ica",
			"Ayacucho",
			"Ancash",
			"San Martin",
			"Lima y Callao",
			"Apurimac",
			"Huanuco",
			"Arequipa",
			"Madre de Dios",
			"Puno",
			"Lambayeque",
			"La Libertad",
			"Cusco",
			"Amazonas",
			"Ucayali",
			"Tumbes",
			"Moquegua",
			"Cajamarca",
			"Tacna",
			"Huancavelica",
			"Piura"
		]
	},
	{
		"name":"Philippines",
		"iso2":"PH",
		"states":[
			"Bicol",
			"Southern Tagalog",
			"Cordillera",
			"Mactan",
			"Bulacan",
			"Southern Mindanao",
			"Caraga",
			"Northern Mindanao",
			"Batangas",
			"Cagayan",
			"Laguna",
			"Ilocos",
			"Central Visayas",
			"Luzon",
			"Western Mindanao",
			"Metropolitan Manila Area",
			"Central Mindanao",
			"Eastern Visayas",
			"Central Luzon",
			"Muslim Mindanao",
			"Davao",
			"Greater Metropolitan Area",
			"Western Visayas"
		]
	},
	{
		"name":"Pitcairn Island",
		"iso2":"PN",
		"states":[
			"Pitcairn Island"
		]
	},
	{
		"name":"Poland",
		"iso2":"PL",
		"states":[
			"Dobroszyce",
			"Rzeszow",
			"Swietokrzyskie",
			"Malomice",
			"Rymanowska",
			"Koscian",
			"Mirkow",
			"Warminsko-Mazurskie",
			"Slaskie",
			"Opolskie",
			"Ostrowiec",
			"Wielkopolskie",
			"Poznan",
			"Hopowo",
			"Pomorskie",
			"Polska",
			"Dziekanow Lesny",
			"Malopolskie",
			"Wejherowo",
			"Stare Pole",
			"Zukowo",
			"Lubelskie",
			"Dolnoslaskie",
			"Wroclaw",
			"Biale Blota",
			"Krakow",
			"Zachodnio-Pomorskie",
			"Kujawsko-Pomorskie",
			"Mazowieckie",
			"Lodzkie",
			"Pruszkow",
			"Kartuzy",
			"Podkarpackie",
			"Podlaskie",
			"Lubuskie",
			"Warsaw"
		]
	},
	{
		"name":"Portugal",
		"iso2":"PT",
		"states":[
			"Distrito de Viana do Castelo",
			"Distrito de Leiria",
			"Abrantes",
			"Norte",
			"Distrito de Vila Real",
			"Centro",
			"Paivas",
			"Algarve",
			"Braga",
			"Madeira",
			"Alentejo",
			"Lisboa e Vale do Tejo",
			"Acores",
			"Distrito do Porto"
		]
	},
	{
		"name":"Puerto Rico",
		"iso2":"PR",
		"states":[
			"San Juan",
			"Guayama",
			"Florida",
			"Salinas",
			"Ponce",
			"Bayamon",
			"Mayaguez-Aguadilla",
			"Humacao",
			"Arecibo",
			"Carolina"
		]
	},
	{
		"name":"Qatar",
		"iso2":"QA",
		"states":[
			"Umm Salal",
			"ad-Dawhah",
			"ar-Rayyan",
			"Doha",
			"al-Ghuwayriyah",
			"al-Khawr",
			"ash-Shamal",
			"Jarian-al-Batnah",
			"al-Jumayliyah",
			"al-Wakrah"
		]
	},
	{
		"name":"Reunion",
		"iso2":"RE",
		"states":[
			"Saint-Paul",
			"Saint-Benoit",
			"Saint-Pierre",
			"Saint-Denis"
		]
	},
	{
		"name":"Romania",
		"iso2":"RO",
		"states":[
			"Valcea",
			"Braila",
			"Suceava",
			"Mures",
			"Sibiu",
			"Hunedoara",
			"Satu Mare",
			"Mehedinti",
			"Vaslui",
			"Bacau",
			"Galati",
			"Botosani",
			"Cluj",
			"Vrancea",
			"Maramures",
			"Teleorman",
			"Buzau",
			"Calarasi",
			"Timis",
			"Constanta",
			"Bistrita-Nasaud",
			"Arges",
			"Covasna",
			"Caras-Severin",
			"Arad",
			"Bihor",
			"Gorj",
			"Prahova",
			"Ilfov",
			"Tulcea",
			"Ialomita",
			"Salaj",
			"Sondelor",
			"Brasov",
			"Dolj",
			"Alba",
			"Neamt",
			"Giurgiu",
			"Harghita",
			"Dambovita",
			"Bucuresti",
			"Olt",
			"Iasi"
		]
	},
	{
		"name":"Russia",
		"iso2":"RU",
		"states":[
			"Primorje",
			"Uljanovsk",
			"Smolensk",
			"Kursk",
			"Samarskaya",
			"Kamchatka",
			"Bashkortostan",
			"Mordovija",
			"Tambov",
			"Voronezh",
			"Burjatija",
			"Astrahan",
			"Moskovskaya Oblast",
			"Karachaj-Cherkessija",
			"Leningrad",
			"Novgorod",
			"Kabardino-Balkarija",
			"Sankt-Peterburg",
			"Orenburg",
			"Rostov",
			"Stavropol",
			"Kalmykija",
			"Chechenija",
			"Krasnodar",
			"Marij El",
			"Moscow",
			"Krasnoyarskiy Kray",
			"Omsk",
			"Komi",
			"Ingusetija",
			"Kaluga",
			"Penza",
			"Murmansk",
			"Tomsk",
			"Chuvashija",
			"Dagestan",
			"Hakasija",
			"Aga",
			"Udmurtija",
			"Tjumen",
			"Pskovskaya Oblast",
			"Gorno-Altaj",
			"Tatarstan",
			"Chukotka",
			"Novosibirsk",
			"Sverdlovsk",
			"Moskva",
			"Kirov",
			"Rjazan",
			"Nizhnij Novgorod",
			"Amur",
			"Tyva",
			"Jevrej",
			"Kostroma",
			"Hanty-Mansija",
			"Altaj",
			"Kurgan",
			"Jaroslavl",
			"Saha",
			"Tver",
			"Vologda",
			"Habarovsk",
			"Perm",
			"Arhangelsk",
			"Cheljabinsk",
			"Chita",
			"Krasnojarsk",
			"Lipeck",
			"Alanija",
			"Moskovskaja Oblast",
			"Belgorod",
			"Ulyanovskaya Oblast",
			"Orjol",
			"Volgograd",
			"Kaliningrad",
			"Ivanovo",
			"Tula",
			"Komi-Permjakija",
			"Sahalin",
			"Tajmyrija",
			"Nenets",
			"Khabarovskiy Kray",
			"Pskov",
			"Brjansk",
			"Vladimir",
			"Novokusnezk",
			"Evenkija",
			"Magadan",
			"Saratov",
			"Korjakija",
			"Adygeja",
			"Jamalo-Nenets",
			"Samara",
			"Karelija",
			"Kemerovo",
			"Ust-Orda",
			"Irkutsk"
		]
	},
	{
		"name":"Rwanda",
		"iso2":"RW",
		"states":[
			"Kigali-ngali",
			"Butare",
			"Cyangugu",
			"Kibungo",
			"Gisenyi",
			"Byumba",
			"Ruhengeri",
			"Gitarama",
			"Gikongoro",
			"Kibuye"
		]
	},
	{
		"name":"Saint Helena",
		"iso2":"SH",
		"states":[
			"Ascension",
			"Gough Island",
			"Saint Helena",
			"Tristan da Cunha"
		]
	},
	{
		"name":"Saint Kitts And Nevis",
		"iso2":"KN",
		"states":[
			"Saint Thomas Lowland",
			"Saint Mary Cayon",
			"Saint Peter Basseterre",
			"Saint Thomas Middle Island",
			"Saint John Figtree",
			"Saint Paul Capesterre",
			"Saint Paul Charlestown",
			"Saint James Windward",
			"Christ Church Nichola Town",
			"Saint George Basseterre",
			"Saint George Gingerland",
			"Trinity Palmetto Point",
			"Saint Anne Sandy Point",
			"Saint John Capesterre"
		]
	},
	{
		"name":"Saint Lucia",
		"iso2":"LC",
		"states":[
			"Vieux Fort",
			"Gros Inlet",
			"Anse-la-Raye",
			"Laborie",
			"Dennery",
			"Soufriere",
			"Castries",
			"Micoud",
			"Canaries",
			"Choiseul"
		]
	},
	{
		"name":"Saint Pierre and Miquelon",
		"iso2":"PM",
		"states":[
			"Miquelon-Langlade",
			"Saint-Pierre"
		]
	},
	{
		"name":"Saint Vincent And The Grenadines",
		"iso2":"VC",
		"states":[
			"Charlotte",
			"Saint George",
			"Saint Patrick",
			"Saint David",
			"Saint Andrew",
			"Grenadines"
		]
	},
	{
		"name":"Saint-Barthelemy",
		"iso2":"BL",
		"states":[]
	},
	{
		"name":"Saint-Martin (French part)",
		"iso2":"MF",
		"states":[]
	},
	{
		"name":"Samoa",
		"iso2":"WS",
		"states":[
			"Vaisigano",
			"Palauli",
			"Fa\\'asaleleaga",
			"Va\\'a-o-Fonoti",
			"A\\'ana",
			"Gaga\\'emauga",
			"Gagaifomauga",
			"Atua",
			"Aiga-i-le-Tai",
			"Tuamasaga",
			"Satupa\\'itea"
		]
	},
	{
		"name":"San Marino",
		"iso2":"SM",
		"states":[
			"Borgo Maggiore",
			"Serravalle",
			"Acquaviva",
			"Domagnano",
			"San Marino",
			"Faetano",
			"Fiorentino",
			"Chiesanuova",
			"Montegiardino"
		]
	},
	{
		"name":"Sao Tome and Principe",
		"iso2":"ST",
		"states":[
			"Cantagalo",
			"Lobata",
			"Me-Zochi",
			"Agua Grande",
			"Pague",
			"Lemba"
		]
	},
	{
		"name":"Saudi Arabia",
		"iso2":"SA",
		"states":[
			"Najran",
			"al-Bahah",
			"Al Khobar",
			"Ash Sharqiyah",
			"al-Madinah",
			"Ha\\'il",
			"Western Province",
			"al-Hudud-ash-Shamaliyah",
			"Makkah",
			"Tabuk",
			"ar-Riyad",
			"Eastern Province",
			"Aseer",
			"Qasim",
			"Jizan",
			"Jawf",
			"Asir",
			"Central Province"
		]
	},
	{
		"name":"Senegal",
		"iso2":"SN",
		"states":[
			"Kaolack",
			"Kolda",
			"Saint-Louis",
			"Thies",
			"Louga",
			"Fatick",
			"Dakar",
			"Diourbel",
			"Tambacounda",
			"Ziguinchor"
		]
	},
	{
		"name":"Serbia",
		"iso2":"RS",
		"states":[
			"Kosovo and Metohija",
			"Central Serbia",
			"Vojvodina"
		]
	},
	{
		"name":"Seychelles",
		"iso2":"SC",
		"states":[
			"Cascade",
			"Anse Royale",
			"Takamaka",
			"Anse Boileau",
			"Victoria"
		]
	},
	{
		"name":"Sierra Leone",
		"iso2":"SL",
		"states":[
			"Southern",
			"Western",
			"Northern",
			"Eastern"
		]
	},
	{
		"name":"Singapore",
		"iso2":"SG",
		"states":[
			"Singapore"
		]
	},
	{
		"name":"Slovakia",
		"iso2":"SK",
		"states":[
			"Nitriansky",
			"Trenciansky",
			"Banskobystricky",
			"Trnavsky",
			"Kosicky",
			"Zilinsky",
			"Presovsky",
			"Bratislavsky"
		]
	},
	{
		"name":"Slovenia",
		"iso2":"SI",
		"states":[
			"Benedikt",
			"Zasavska",
			"Obcina Vitanje",
			"Koroshka",
			"Pomurska",
			"Spodnjeposavska",
			"Obalno-krashka",
			"Jugovzhodna Slovenija",
			"Slovenian Littoral",
			"Podravska",
			"Obcina Domzale",
			"Notranjsko-krashka",
			"Savinjska",
			"Gorishka",
			"Gorenjska",
			"Osrednjeslovenska"
		]
	},
	{
		"name":"Solomon Islands",
		"iso2":"SB",
		"states":[
			"Central",
			"Rennell and Bellona",
			"Makira and Ulawa",
			"Isabel",
			"Malaita",
			"Choiseul",
			"Temotu",
			"Guadalcanal",
			"Western"
		]
	},
	{
		"name":"Somalia",
		"iso2":"SO",
		"states":[
			"Nugal",
			"Jubbadha Dexe",
			"Banadir",
			"Mudug",
			"Togdher",
			"Hiran",
			"Woqoyi Galbed",
			"Bay",
			"Jubbada Hose",
			"Awdal",
			"Galgudug",
			"Bakol",
			"Gedo",
			"Bari",
			"Shabellaha Hose",
			"Sanag",
			"Shabellaha Dhexe"
		]
	},
	{
		"name":"South Africa",
		"iso2":"ZA",
		"states":[
			"Gauteng",
			"Parow",
			"KwaZulu Natal",
			"Western Cape",
			"Umtentweni",
			"Eastern Cape",
			"Kramerville",
			"North West",
			"Limpopo",
			"Kempton Park",
			"Mpumalanga",
			"Table View",
			"Northern Cape",
			"Free State"
		]
	},
	{
		"name":"South Georgia",
		"iso2":"GS",
		"states":[
			"South Georgia"
		]
	},
	{
		"name":"South Sudan",
		"iso2":"SS",
		"states":[
			"Central Equatoria"
		]
	},
	{
		"name":"Spain",
		"iso2":"ES",
		"states":[
			"Biscay",
			"Pontevedra",
			"Granada",
			"Palencia",
			"Andalucia",
			"Badajoz",
			"Guadalajara",
			"Balears",
			"Santa Cruz de Tenerife",
			"Caceres",
			"Vizcaya",
			"Toledo",
			"Barcelona",
			"Valencia",
			"Gipuzkoa",
			"Bertamirans",
			"Lugo",
			"Malaga",
			"Zaragoza",
			"Comunidad Autonoma de Cataluna",
			"Jaen",
			"Salamanca",
			"Cordoba",
			"Tenerife",
			"Girona",
			"Lleida",
			"Comunidad Autonoma de las Isla",
			"Teruel",
			"Huesca",
			"Valladolid",
			"Navarra",
			"Ourense",
			"Comunidad Autonoma de Canarias",
			"Zamora",
			"Cuenca",
			"Guipuzcoa",
			"Tarragona",
			"Murcia",
			"Comunidad Valenciana",
			"Alacant",
			"Cadiz",
			"Ciudad Real",
			"A Coruna",
			"Asturias",
			"Ceuta",
			"Comunidad Autonoma de Galicia",
			"Pais Vasco",
			"Avila",
			"Castello",
			"Segovia",
			"Soria",
			"Las Palmas",
			"Huelva",
			"Albacete",
			"Burgos",
			"Melilla",
			"Comunidad Autonoma del Princip",
			"Lerida",
			"Sevilla",
			"Catalunya",
			"Leon",
			"La Rioja",
			"Alava",
			"Madrid",
			"Cantabria",
			"Almeria"
		]
	},
	{
		"name":"Sri Lanka",
		"iso2":"LK",
		"states":[
			"North Western Province",
			"Matara",
			"Western Province",
			"Galla",
			"Ratnapuraya",
			"Puttalama",
			"Matale",
			"Maha Nuwara",
			"Southern Province",
			"Polonnaruwa",
			"Monaragala",
			"Tirikunamalaya",
			"Kilinochchi",
			"Kegalla",
			"Mannarama",
			"Tuscany",
			"Boralesgamuwa",
			"Kurunegala",
			"Malwana",
			"Mullaitivu",
			"Amparai",
			"North Eastern Province",
			"Badulla",
			"Vavuniyawa",
			"Anuradhapuraya",
			"Kalatura",
			"Colombo",
			"Gampaha",
			"Nuwara Eliya",
			"Hambantota",
			"Madakalpuwa",
			"Yapanaya",
			"kadawatha"
		]
	},
	{
		"name":"Sudan",
		"iso2":"SD",
		"states":[
			"al-Buhayrat",
			"al-Qadarif",
			"Gharb Bahr-al-Ghazal",
			"A\\'ali-an-Nil",
			"Warab",
			"Shamal Darfur",
			"Central Equatoria",
			"Nahr-an-Nil",
			"Bahr-al-Jabal",
			"Sinnar",
			"Shamal Bahr-al-Ghazal",
			"al-Khartum",
			"Janub Darfur",
			"Shamal Kurdufan",
			"Janub Kurdufan",
			"Junqali",
			"an-Nil-al-Azraq",
			"Gharb Kurdufan",
			"Gharb Darfur",
			"ash-Shamaliyah",
			"Gharb-al-Istiwa\\'iyah",
			"Wilayat al Khartum",
			"al-Wahdah",
			"al-Bahr-al-Ahmar",
			"Kassala",
			"al-Jazirah",
			"Sharq-al-Istiwa\\'iyah",
			"an-Nil-al-Abyad"
		]
	},
	{
		"name":"Suriname",
		"iso2":"SR",
		"states":[
			"Commewijne",
			"Saramacca",
			"Coronie",
			"Para",
			"Brokopondo",
			"Wanica",
			"Marowijne",
			"Paramaribo",
			"Nickerie"
		]
	},
	{
		"name":"Svalbard And Jan Mayen Islands",
		"iso2":"SJ",
		"states":[
			"Svalbard"
		]
	},
	{
		"name":"Swaziland",
		"iso2":"SZ",
		"states":[
			"Lubombo",
			"Hhohho",
			"Manzini",
			"Shiselweni"
		]
	},
	{
		"name":"Sweden",
		"iso2":"SE",
		"states":[
			"Uppsala",
			"Vastra Gotaland",
			"Saltsjo-Boo",
			"Gotland",
			"Gaza",
			"Norrbotten",
			"Vasterbotten",
			"Kristianstads",
			"Vastmanland",
			"Vasternorrland",
			"Bohuslan",
			"Jamtland",
			"Kronoberg",
			"Blekinge",
			"Halland",
			"Gavleborg",
			"Smaland",
			"Kalmar",
			"Sodermanland",
			"Angermanland",
			"Ostergotland",
			"Varmland",
			"Stockholm",
			"Jonkoping",
			"Skane",
			"Orebro",
			"Dalarna",
			"Alvsborgs Lan",
			"Vastergotland"
		]
	},
	{
		"name":"Switzerland",
		"iso2":"CH",
		"states":[
			"Neuchatel",
			"Morbio Inferiore",
			"Muhen",
			"Schaffhausen",
			"Valais",
			"Schwyz",
			"Solothurn",
			"Appenzell Inner-Rhoden",
			"Geneve",
			"Aargau",
			"Fribourg",
			"Basel-Landschaft",
			"Thurgau",
			"Luzern",
			"Vaud",
			"Basel-Stadt",
			"Bern",
			"Jura",
			"Heerbrugg",
			"Sankt Gallen",
			"Graubunden",
			"Ticino",
			"Uri",
			"Appenzell-Ausser Rhoden",
			"Zug",
			"Canton Ticino",
			"Glarus",
			"Kanton Aargau",
			"Zurich",
			"Nidwalden",
			"Obwalden",
			"Vauffelin"
		]
	},
	{
		"name":"Syria",
		"iso2":"SY",
		"states":[
			"Madinat Dimashq",
			"Dayr-az-Zawr",
			"Aleppo",
			"as-Suwayda",
			"Idlib",
			"Dar\\'a",
			"Hims",
			"al-Hasakah",
			"Hamah",
			"ar-Raqqah",
			"al-Ladhiqiyah",
			"Dimashq",
			"Tartus",
			"Halab",
			"al-Qunaytirah"
		]
	},
	{
		"name":"Taiwan",
		"iso2":"TW",
		"states":[
			"Tainan Hsien",
			"Keelung Shih",
			"Kaohsiung Shih",
			"Taipei Hsien",
			"Penghu",
			"Changhwa",
			"Chiayi Hsien",
			"Eastern Taipei",
			"Pingtung",
			"Taipei Shih / Taipei Hsien",
			"Northern Taiwan",
			"Yunlin",
			"Kaohsiung Hsien",
			"Ilan",
			"Yun-Lin Hsien",
			"Hsinchu Hsien",
			"Taichung Hsien",
			"Taitung",
			"Kinmen",
			"Miaoli",
			"Taichung",
			"Yilan",
			"Tainan Shih",
			"Hualien",
			"Nantou",
			"Taichung Shih",
			"Taoyuan",
			"Hsinchu Shih",
			"Chiayi Shih"
		]
	},
	{
		"name":"Tajikistan",
		"iso2":"TJ",
		"states":[
			"Sughd",
			"Gorno-Badakhshan",
			"Dushanbe",
			"Karotegin",
			"Khatlon"
		]
	},
	{
		"name":"Tanzania",
		"iso2":"TZ",
		"states":[
			"Mwanza",
			"Kagera",
			"Tabora",
			"Mara",
			"Arusha",
			"Mbeya",
			"Morogoro",
			"Ruvuma",
			"Iringa",
			"Zanzibar and Pemba",
			"Shinyanga",
			"Dar es Salaam",
			"Lindi",
			"Kilimanjaro",
			"Tanga",
			"Kigoma",
			"Rukwa",
			"Dodoma",
			"Pwani",
			"Singida",
			"Mtwara"
		]
	},
	{
		"name":"Thailand",
		"iso2":"TH",
		"states":[
			"Phichit",
			"Prachuap Khiri Khan",
			"Mukdahan",
			"Ubon Ratchathani",
			"Lamphun",
			"Nan",
			"Phitsanulok",
			"Chanthaburi",
			"Changwat Chaiyaphum",
			"Chachoengsao",
			"Phatthalung",
			"Si Sa Ket",
			"Pattani",
			"Sakon Nakhon",
			"Phetchaburi",
			"Nakhon Ratchasima",
			"Songkhla",
			"Kamphaeng Phet",
			"Chiang Rai",
			"Kalasin",
			"Amnat Charoen",
			"Chumphon",
			"Mae Hong Son",
			"Khon Kaen",
			"Satun",
			"Phra Nakhon Si Ayutthaya",
			"Surin",
			"Ang Thong",
			"Uttaradit",
			"Sa Kaeo",
			"Bangkok",
			"Roi Et",
			"Ratchaburi",
			"Nakhon Pathom",
			"Surat Thani",
			"Prachin Buri",
			"Maha Sarakham",
			"Sing Buri",
			"Tak",
			"Loei",
			"Udon Thani",
			"Sukhothai",
			"Phrae",
			"Chon Buri",
			"Suphan Buri",
			"Pathum Thani",
			"Krabi",
			"Yala",
			"Nonthaburi",
			"Nakhon Si Thammarat",
			"Phangnga",
			"Nakhon Phanom",
			"Lop Buri",
			"Phayao",
			"Narathiwat",
			"Nakhon Nayok",
			"Chaiyaphum",
			"Uthai Thani",
			"Nong Bua Lam Phu",
			"Trat",
			"Buri Ram",
			"Ranong",
			"Nong Khai",
			"Yasothon",
			"Chai Nat",
			"Saraburi",
			"Rayong",
			"Phetchabun",
			"Trang",
			"Phuket",
			"Lampang",
			"Nakhon Sawan",
			"Samut Prakan",
			"Samut Songkhran",
			"Krung Thep",
			"Chiang Mai",
			"Samut Sakhon",
			"Kanchanaburi"
		]
	},
	{
		"name":"Togo",
		"iso2":"TG",
		"states":[
			"Kara",
			"Savanes",
			"Plateaux",
			"Maritime",
			"Centre"
		]
	},
	{
		"name":"Tokelau",
		"iso2":"TK",
		"states":[
			"Fakaofo",
			"Nukunonu",
			"Atafu"
		]
	},
	{
		"name":"Tonga",
		"iso2":"TO",
		"states":[
			"Niuas",
			"Ha\\'apai",
			"Eua",
			"Tongatapu",
			"Vava\\'u"
		]
	},
	{
		"name":"Trinidad And Tobago",
		"iso2":"TT",
		"states":[
			"Point Fortin",
			"San Juan",
			"Penal Debe",
			"Glencoe",
			"Saint George",
			"Chaguanas",
			"Siparia",
			"Tobago",
			"Princes Town",
			"San Fernando",
			"Couva-Tabaquite-Talparo",
			"Arima-Tunapuna-Piarco",
			"Port of Spain",
			"Sangre Grande",
			"Caroni",
			"Diego Martin"
		]
	},
	{
		"name":"Tunisia",
		"iso2":"TN",
		"states":[
			"Gouvernorat de Sousse",
			"Bin \\'Arus",
			"Gouvernorat de Nabeul",
			"Zaghwan",
			"Hammamet Yasmine",
			"Sidi Bu Zayd",
			"Binzart",
			"Qibili",
			"al-Qayrawan",
			"al-Munastir",
			"Silyanah",
			"Susah",
			"Gouvernorat de Ariana",
			"Tatawin",
			"Aryanah",
			"Sfax",
			"Qabis",
			"Jundubah",
			"Monastir",
			"Tunis",
			"al-Qasrayn",
			"Qafsah",
			"Bajah",
			"Nabul",
			"Safaqis",
			"al-Kaf",
			"Manubah",
			"Madaniyin",
			"Tawzar",
			"al-Mahdiyah"
		]
	},
	{
		"name":"Turkey",
		"iso2":"TR",
		"states":[
			"Karaman",
			"Van",
			"Istanbul",
			"Erzurum",
			"Artvin",
			"Kahramanmaras",
			"Manisa",
			"Mus",
			"Ardahan",
			"Icel",
			"Karabuk",
			"Hakkari",
			"Adiyaman",
			"Gaziantep",
			"Diyarbakir",
			"Balikesir",
			"Ordu",
			"Tekirdag",
			"Siirt",
			"Sinop",
			"Usak",
			"Eskisehir",
			"Cankiri",
			"Isparta",
			"Sanliurfa",
			"Bingol",
			"Bayburt",
			"Kayseri",
			"Batman",
			"Kocaeli",
			"Mardin",
			"Afyon",
			"Ankara",
			"Hatay",
			"Sakarya",
			"Bolu",
			"Kutahya",
			"Corum",
			"Rize",
			"Tokat",
			"Igdir",
			"Bitlis",
			"Bilecik",
			"Trabzon",
			"Kirklareli",
			"Bartin",
			"Kirikkale",
			"Giresun",
			"Samsun",
			"Elazig",
			"Erzincan",
			"Aydin",
			"Duzce",
			"Osmaniye",
			"Kirsehir",
			"Kastamonu",
			"Mugla",
			"Nevsehir",
			"Gumushane",
			"Aksaray",
			"Tunceli",
			"Zonguldak",
			"Kars",
			"Denizli",
			"Yalova",
			"Malatya",
			"Sirnak",
			"Lefkosa",
			"Kilis",
			"Amasya",
			"Adana",
			"Sivas",
			"Nigde",
			"Bursa",
			"Edirne",
			"Canakkale",
			"Agri",
			"Antalya",
			"Burdur",
			"Konya",
			"Yozgat",
			"Karsiyaka",
			"Izmir"
		]
	},
	{
		"name":"Turkmenistan",
		"iso2":"TM",
		"states":[
			"Ahal",
			"Balkan",
			"Mari",
			"Dasoguz",
			"Asgabat",
			"Lebap"
		]
	},
	{
		"name":"Turks And Caicos Islands",
		"iso2":"TC",
		"states":[
			"Grand Turk",
			"South Caicos and East Caicos"
		]
	},
	{
		"name":"Tuvalu",
		"iso2":"TV",
		"states":[
			"Nanumanga",
			"Niutao",
			"Nukufetau",
			"Funafuti",
			"Vaitupu",
			"Nui",
			"Nanumea",
			"Nukulaelae"
		]
	},
	{
		"name":"Uganda",
		"iso2":"UG",
		"states":[
			"Central",
			"Western",
			"Northern",
			"Eastern"
		]
	},
	{
		"name":"Ukraine",
		"iso2":"UA",
		"states":[
			"Volyns\\'ka",
			"Khersonska",
			"Zakarpats\\'ka",
			"Kyyiv",
			"Odes\\'ka",
			"Odessa",
			"Krym",
			"Zhytomyrs\\'ka",
			"Chernivets\\'ka",
			"Kirovohrad",
			"Sums\\'ka",
			"Ivano-Frankivs\\'ka",
			"Mykolayivs\\'ka",
			"Donets\\'ka",
			"Kharkov",
			"Kyyivs\\'ka",
			"Kharkiv",
			"Vynnyts\\'ka",
			"Cherkas\\'ka",
			"Zaporizhia",
			"Luhans\\'ka",
			"Sevastopol\\'",
			"Poltavs\\'ka",
			"Ternopil\\'s\\'ka",
			"Rivnens\\'ka",
			"Crimea",
			"Khmel\\'nyts\\'ka",
			"Dnipropetrovska",
			"L\\'vivs\\'ka",
			"Chernihivs\\'ka"
		]
	},
	{
		"name":"United Arab Emirates",
		"iso2":"AE",
		"states":[
			"Ajman",
			"Sharjah",
			"Ras al-Khaymah",
			"Sharjha",
			"Umm al Qaywayn",
			"Dubai",
			"ash-Shariqah",
			"Abu Zabi",
			"al-Fujayrah"
		]
	},
	{
		"name":"United Kingdom",
		"iso2":"GB",
		"states":[
			"Merseyside",
			"Hants",
			"Wrexham",
			"Mayfair",
			"Lanarkshire",
			"Armagh",
			"Yorkshire",
			"Mildenhall",
			"Kent",
			"West Yorkshire",
			"Channel Islands",
			"Llanymynech",
			"Devon",
			"Dorset",
			"Hertfordshire",
			"Roos-shire",
			"Norfolk",
			"Dial Code Dungannon",
			"Flintshire",
			"Cambridgeshire",
			"Glocestershire",
			"England",
			"Kenford",
			"East Midlands",
			"West Midlands",
			"Argyll",
			"Fife",
			"Durham",
			"Manchester",
			"Northamptonshire",
			"Gwent",
			"Wurttemberg",
			"Denbighshire",
			"Somerset",
			"Worcestershire",
			"Southwell",
			"North Humberside",
			"Kilmarnock",
			"East Sussex",
			"London",
			"Wiltshire",
			"Northumberland",
			"Staffordshire",
			"Scottish Borders",
			"Cheshire",
			"Northants",
			"Cambridge",
			"South Yorkshire",
			"Essex",
			"Cumbria",
			"North Yorkshire",
			"Whissendine",
			"Nottinghamshire",
			"Aberdeen",
			"Belfast",
			"East Lothian",
			"Aberdeenshire",
			"Co Fermanagh",
			"Scotland",
			"East Yorkshire",
			"Conwy",
			"Ireland",
			"Bedfordshire",
			"Wales",
			"Newton Stewart",
			"Bridgnorth",
			"Warwickshire",
			"Gainsborough",
			"Strabane",
			"Mid Glamorgan",
			"Buckinghamshire",
			"Didcot",
			"Herefordshire",
			"West Lothian",
			"Twickenham",
			"Dunbartonshire",
			"Shropshire",
			"Powys",
			"Lancashire",
			"Derbyshire",
			"Surrey",
			"Monmouthshire",
			"Fermanagh",
			"Birmingham",
			"Cleveland",
			"Sark",
			"Wokingham",
			"Isle Of Man",
			"Middlesex",
			"Berkshire",
			"Hampshire",
			"Tyrone",
			"South Wales",
			"Isle of Wight",
			"East Dunbartonshire",
			"West Sussex",
			"Lincolnshire",
			"Craven Arms",
			"Utah",
			"Cornwall",
			"Fulham",
			"Oxford",
			"Brechin",
			"SUSSEX",
			"Coventry",
			"Ludlow",
			"Bristol",
			"Derby",
			"Leicestershire",
			"Tyne and Wear",
			"South Glamorgan",
			"Suffolk",
			"Northern Ireland"
		]
	},
	{
		"name":"United States",
		"iso2":"US",
		"states":[
			"Federated States Of Micronesia",
			"Mississippi",
			"Ontario",
			"Palau",
			"Northern Mariana Islands",
			"South Dakota",
			"Oklahoma",
			"Delaware",
			"Minnesota",
			"Illinois",
			"Arkansas",
			"New Mexico",
			"New Hampshire",
			"Indiana",
			"Maryland",
			"Louisiana",
			"Idaho",
			"Wyoming",
			"Tennessee",
			"Arizona",
			"Iowa",
			"Lowa",
			"Michigan",
			"Kansas",
			"Utah",
			"American Samoa",
			"Oregon",
			"Connecticut",
			"Montana",
			"California",
			"Massachusetts",
			"Puerto Rico",
			"South Carolina",
			"Marshall Islands",
			"Wisconsin",
			"Vermont",
			"Georgia",
			"North Dakota",
			"Pennsylvania",
			"Byram",
			"West Virginia",
			"Florida",
			"Hawaii",
			"Kentucky",
			"Alaska",
			"Texas",
			"Sublimity",
			"Nebraska",
			"Medfield",
			"Missouri",
			"Ohio",
			"Alabama",
			"New York",
			"New Jersy",
			"Virgin Islands",
			"Ramey",
			"Colorado",
			"New Jersey",
			"Virginia",
			"Guam",
			"Washington",
			"North Carolina",
			"Trimble",
			"District of Columbia",
			"Cokato",
			"Nevada",
			"Maine",
			"Rhode Island"
		]
	},
	{
		"name":"United States Minor Outlying Islands",
		"iso2":"UM",
		"states":[
			"United States Minor Outlying I"
		]
	},
	{
		"name":"Uruguay",
		"iso2":"UY",
		"states":[
			"Salto",
			"Treinta y Tres",
			"Cerro Largo",
			"Colonia",
			"Lavalleja",
			"Rio Negro",
			"San Jose",
			"FLorida",
			"Paysandu",
			"Durazno",
			"Tacuarembo",
			"Maldonado",
			"Flores",
			"Rocha",
			"Montevideo",
			"Soriano",
			"Artigas",
			"Rivera",
			"Canelones"
		]
	},
	{
		"name":"Uzbekistan",
		"iso2":"UZ",
		"states":[
			"Cizah",
			"Namangan",
			"Horazm",
			"Buxoro Viloyati",
			"Fargona",
			"Samarkand",
			"Korakalpogiston",
			"Navoi",
			"Surhondar",
			"Sirdare",
			"Andijon",
			"Buhoro",
			"Kaskadar",
			"Toskent"
		]
	},
	{
		"name":"Vanuatu",
		"iso2":"VU",
		"states":[
			"Tafea",
			"Shefa",
			"Malampa",
			"Torba",
			"Penama",
			"Sanma"
		]
	},
	{
		"name":"Vatican City State (Holy See)",
		"iso2":"VA",
		"states":[
			"Vatican City State (Holy See)"
		]
	},
	{
		"name":"Venezuela",
		"iso2":"VE",
		"states":[
			"Delta Amacuro",
			"Guarico",
			"Bolivar",
			"Lara",
			"Aragua",
			"Yaracuy",
			"Monagas",
			"Miranda",
			"Falcon",
			"Anzoategui",
			"Vargas",
			"Apure",
			"Amazonas",
			"Cojedes",
			"Nueva Esparta",
			"Sucre",
			"Merida",
			"Barinas",
			"Distrito Federal",
			"Zulia",
			"Tachira",
			"Trujillo",
			"Portuguesa",
			"Carabobo"
		]
	},
	{
		"name":"Vietnam",
		"iso2":"VN",
		"states":[
			"Tinh Gia Lai",
			"Binh Duong",
			"Dong Bang Song Cuu Long",
			"Tinh Can Tho",
			"Tinh Da Nang",
			"Hanoi",
			"Binh Dinh",
			"Dong Nai",
			"Thai Nguyen",
			"Dong Bang Song Hong",
			"Long An",
			"Thu Do Ha Noi",
			"Khu Bon Cu",
			"Dong Nam Bo",
			"Duyen Hai Mien Trung",
			"Bac Giang",
			"Hung Yen",
			"Mien Nui Va Trung Du",
			"Da Nang",
			"Thanh Pho Ho Chi Minh"
		]
	},
	{
		"name":"Virgin Islands (British)",
		"iso2":"VG",
		"states":[
			"Anegada",
			"Tortola",
			"Jost van Dyke"
		]
	},
	{
		"name":"Virgin Islands (US)",
		"iso2":"VI",
		"states":[
			"Saint John",
			"Saint Croix",
			"Saint Thomas"
		]
	},
	{
		"name":"Wallis And Futuna Islands",
		"iso2":"WF",
		"states":[
			"Alo",
			"Wallis",
			"Singave"
		]
	},
	{
		"name":"Western Sahara",
		"iso2":"EH",
		"states":[
			"Bu Jaydur",
			"Wad-adh-Dhahab",
			"al-\\'Ayun",
			"as-Samarah"
		]
	},
	{
		"name":"Yemen",
		"iso2":"YE",
		"states":[
			"Hajjah",
			"Lahij",
			"Sana",
			"Ma\\'rib",
			"Abyan",
			"al-Hudaydah",
			"Ta\\'izz",
			"al-Bayda",
			"Ibb",
			"Hudaydah",
			"Shabwah",
			"\\'Adan",
			"Sa\\'dah",
			"Dhamar",
			"Madinat San\\'a",
			"al-Mahwit",
			"Hadramaut",
			"al-Mahrah",
			"al-Jawf"
		]
	},
	{
		"name":"Zambia",
		"iso2":"ZM",
		"states":[
			"Central",
			"Northern",
			"Eastern",
			"North-Western",
			"Southern",
			"Western",
			"Luapala",
			"Copperbelt",
			"Lusaka"
		]
	},
	{
		"name":"Zimbabwe",
		"iso2":"ZW",
		"states":[
			"Bulawayo",
			"Mashonaland Central",
			"Harare",
			"Matabeleland North",
			"Matabeleland South",
			"Mashonaland East",
			"Masvingo",
			"Manicaland",
			"Midlands",
			"Mashonaland West"
		]
	}
]

